### ISSUE TITLE
`TypeError: expected string or bytes-like object` in many PDM commands

### ISSUE THREAD

**Issue by gjoseph92** [pdm-project/pdm#1385] opened 2022-09-14 22:24 UTC
- [x] I have searched the issue tracker and believe that this is not a duplicate.

Seems similar to https://github.com/pdm-project/pdm/issues/935. 

**Make sure you run commands with `-v` flag before pasting the output.**

Most PDM commands are currently failing for me with this error:
```python-traceback
  File "/Users/gabe/.local/bin/pdm", line 10, in <module>
    sys.exit(main())
  File "/Users/gabe/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 254, in main
    return Core().main(args)
  File "/Users/gabe/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 187, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/Users/gabe/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 182, in main
    f(options.project, options)
  File "/Users/gabe/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/cli/commands/install.py", line 61, in handle
    actions.do_sync(
  File "/Users/gabe/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 208, in do_sync
    handler = project.core.synchronizer_class(
  File "/Users/gabe/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 121, in __init__
    self.working_set = environment.get_working_set()
  File "/Users/gabe/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/models/environment.py", line 174, in get_working_set
    return WorkingSet([paths["platlib"], paths["purelib"]])
  File "/Users/gabe/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/models/working_set.py", line 74, in __init__
    self._dist_map = {
  File "/Users/gabe/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/models/working_set.py", line 75, in <dictcomp>
    normalize_name(dist.metadata["Name"]): dist
  File "/Users/gabe/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/utils.py", line 382, in normalize_name
    name = re.sub(r"[^A-Za-z0-9.]+", "-", name)
  File "/Users/gabe/.pyenv/versions/3.9.1/lib/python3.9/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

Unfortunately, I don't have a way to reproduce this. Copying the `pyproject.toml` and `pdm.lock` to a new directory and installing them, it works fine.

However, if I also copy over the `.venv` directory, then I again see the error. So the issue has something to do with the set of packages currently installed in the virtual environment (which makes sense, given what this method is doing). I haven't been able to figure out a set of steps to break the environment in this way.

I manually edited `working_set.py` to:
```python
class WorkingSet(Mapping[str, im.Distribution]):
    """A dictionary of currently installed distributions"""

    def __init__(self, paths: list[str] | None = None):
        if paths is None:
            paths = sys.path
        # EDIT: print bad distributions
        for dist in distributions(path=paths):
            if not dist.metadata["Name"]:
                print(dict(dist.metadata))
        # END EDIT
        self._dist_map = {
            normalize_name(dist.metadata["Name"]): dist
            for dist in distributions(path=paths)
        }
```

Re-running a command like `pdm install -v -G:all`, I get:
```
pdm.termui: Using cached wheel: /Users/gabe/Library/Caches/pdm/wheels/d7/a1/3e/2d510c52c4417e456e8b5a3c79531dd2b76240b0e797ad1b4c/sneks_sync-0.2.0-py3-none-any.whl
{}
{}
Traceback (most recent call last):
...
TypeError: expected string or bytes-like object
```

The `{}` imply that somehow, there are `Distribution` objects floating around with no metadata.

I feel like maybe PDM should be robust to this situation, and just ignore distributions that it finds which are missing metadata. Without understanding exactly how this happens though, it's hard to say. Apologies for not being able to find a reproducer for this.

For now, I've just deleted and re-created the venv, and it's now working fine.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.1.3
Python Interpreter:
  /Users/gabe/dev/snakebench/.venv/bin/python (3.9)
Project Root:
  /Users/gabe/dev/snakebench
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.4",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "21.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64",
  "python_full_version": "3.9.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment] 2022-09-15 02:23
You can print `dist._path` to see the exact file with broken metatada, but since you recreated the venv and can't reproduce it any more, I am going to close this one.

**Closed by frostming** 2022-09-15 02:23 UTC
Labels: bug

**Comment by abinavrameshs** [comment] 2022-11-23 20:32
I am getting the same error too..
Please find the pyproject.toml and pdm.lock files

Environment : Python 3.10.7
Platform : Windows 10

[pdm files.zip](https://github.com/pdm-project/pdm/files/10079004/pdm.files.zip)

**Comment by Indiana3714** [comment] 2023-01-11 22:07
Having the same errors too in many instances. Kind of makes me want to return back to Poetry even though it's slower.

Steps to reproduce:
1) `pdm install`
2) `pdm run python xxx.py` - Run the python program using pdm
3) Update one of your Python library dependencies by incrementing their version number
4) `pdm update` - Run this while the python program from (2) is still running, this will expectedly raise something similar to `PermissionError: [WinError 5] Access is denied:`
5) Close the Python program started from (2)
6) `pdm update` and `pdm install` is now forever broken from here forward regardless of how many times it is called

I believe it boils down to PDM not restoring the original config files if it encounters any errors, leading to partially broken config files?

Hoping this thread can be reopened now, instead of having to create a new thread

**Comment by frostming** [comment] 2023-01-12 00:49
@Indiana3714 To reproduce it, you need to provide more information

1. Does it reproduce consistently with the said steps?
2. What is the dependencies set of your project? Or if it doesn't matter at all?
