### ISSUE TITLE
pdm install fails against package index requiring authentication when pdm.lock file is present

### ISSUE THREAD

**Issue by michaelze** [pdm-project/pdm#1747] opened 2023-03-03 06:33 UTC
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

- Add an additional package index to your `pyproject.toml` that requires authentication

```
[[tool.pdm.source]]
name = "internal"
url = "https://${REPO_USER}:${REPO_PASSWORD}@..."
verify_ssl = true
```

- Add a dependency that must be installed from the additional package index
- Run `python -m pdm install`
- Remove the `.venv` folder
- Run `python -m pdm install` again

## Actual behavior

The first `pdm install` succeeds and creates a `pdm.lock` file.
The second `pdm install` fails with

```
Traceback (most recent call last):
  File "C:\dev\python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\dev\python\Python310\lib\site-packages\pdm\installers\synchronizers.py", line 236, in install_candidate
    self.manager.install(can)
  File "C:\dev\python\Python310\lib\site-packages\pdm\installers\manager.py", line 39, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "C:\dev\python\Python310\lib\site-packages\pdm\models\candidates.py", line 363, in build
    self.obtain(allow_all=False)
  File "C:\dev\python\Python310\lib\site-packages\pdm\models\candidates.py", line 432, in obtain
    result = finder.download_and_unpack(
  File "C:\dev\python\Python310\lib\site-packages\unearth\finder.py", line 358, in download_and_unpack
    file = unpack_link(
  File "C:\dev\python\Python310\lib\site-packages\unearth\preparer.py", line 304, in unpack_link
    raise UnpackError(f"Download failed: {e}") from None
unearth.errors.UnpackError: Download failed: 403 Client Error:  for url: https://...
```

## Expected behavior

The installation from a `pdm.lock` file should also work against package indexes requiring authentication.

## Environment Information

```bash
PDM version:
  2.4.7
Python Interpreter:
  C:\dev\workspaces\<redacted>\.venv\Scripts\python.exe (3.10)
Project Root:
  C:/dev/workspaces/<redacted>
Project Packages:
  None

{
  "implementation_name": "cpython",
  "implementation_version": "3.10.5",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19045",
  "python_full_version": "3.10.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "win32"
}
```

**Comment by noirbizarre** [comment] 2023-03-03 10:16
I have the same issue with GemFury private registries, but with 404 instead of 403:

```
ERRORS:
add xxxxx failed:
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
See /tmp/pdm-install-5pjxu_n5.log for detailed debug log.
  File 
"/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/
synchronizers.py", line 230, in install_candidate
    self.manager.install(can)
  File 
"/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/
manager.py", line 33, in install
[InstallationError]: Some package operations are not complete yet
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File 
"/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/cand
idates.py", line 360, in build
    self.obtain(allow_all=False)
Add '-v' to see the detailed traceback
  File 
"/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/cand
idates.py", line 419, in obtain
    result = finder.download_and_unpack(self.link, build_dir, download_dir, 
hash_options)
  File 
"/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/unearth/finder.
py", line 359, in download_and_unpack
    file = unpack_link(
  File 
"/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/unearth/prepare
r.py", line 304, in unpack_link
    raise UnpackError(f"Download failed: {e}") from None
unearth.errors.UnpackError: Download failed: 404 Client Error: Not Found for 
url: https://pypi.fury.io/xxxxxx/-/xxxxxx/xxxxxxxxxxxx-1.yy.0.tar.gz
```

To reproduce:
- create a private registry on [Gemfury](https://gemfury.com/) (The trial allows it)
- publish a package on it
- create pdm-based project with the registry declared as a `tool.pdm.source`
- install the private dependency > works just fine
- drop the venv
- `pdm sync` > fails to get the dependency with the above stacktrace 👆🏼 

To work around this, I need to:
- drop the venv
- run `pdm cache clear`
- then `pdm sync` or `install` should work

**Comment by frostming** [comment] 2023-03-04 09:00
@noirbizarre 

It's weird, I found a [different bug](https://github.com/frostming/unearth/commit/3433a7730cffd3b6c49bbabf57469c719a237be6) from what you posted, but after I patched it the installation just works fine.

**Comment by frostming** [comment] 2023-03-04 09:32
I might find out something. In most repositories, accessing `<index_url>/<package>` returns 401 resp if auth isn't given, while downloading `<index_url>/<package_file_url>` returns 403. And PDM will try to get the auth from the source URL before the request, so the problem is PDM fails to find the matching source(using prefix matching) for the file URL. The causes might be:

1. Due to [the bug in unearth](https://github.com/frostming/unearth/commit/3433a7730cffd3b6c49bbabf57469c719a237be6), the empty password will be ignored.
2. The file URL uses a different prefix from the index. For example, PyPI index is `https://pypi.org/simple` while the file URLs start with `https://files.pythonhosted.org`

**Comment by noirbizarre** [comment] 2023-03-04 19:44
I should be able to test this on monday.
I think Gemfury deliberately chose to return 404 instead of 403 to perform security by secrecy (you can't poll URLs).

My hypothesis (I need to dig the code to see if this is a real possiblity) is that there is 2 flows:

Cold cache:
- URL from lock is tried 
- gemfury return 404
- 404 response is cached (I think this is somehow an issue, 404 should not be cached, but I didn't dig the code yet, so still an hypothesis)
- 404 don't trigger an auth and end the flow

Hot cache:
- URL is tried from lock
- 404 is hit from cache

Note: it doesn't seem to happen if you are the one initially installing the package. Seems logical as you don't hit/cache the 404 but the package itself because install properly inject credentials.

**Comment by frostming** [comment] 2023-03-05 00:17
> * 404 is hit from cache

No, only (200, 203, 300, 301, 308) will be cached

**Comment by noirbizarre** [comment] 2023-03-05 16:47
So maybe there are 2 distinct issues: given Gemfury use an empty password, maybe the current fix is enough for my case (but I agree that the fact we need to clear the cache to make it work is weird). I'll try tomorrow.

**Comment by michaelze** [comment] 2023-03-06 08:04
>     2. The file URL uses a different prefix from the index. For example, PyPI index is `https://pypi.org/simple` while the file URLs start with `https://files.pythonhosted.org`

I investigated this issue a little deeper and think you might be onto something with your second suspicion. As we are hosting the registry I'm trying to download from ourselves, I also have access to its request logs:

- the url in the [[pdm.tool.source]] section is "https://${REPO_USER}:${REPO_PASSWORD}@.../simple"

`pdm install` without a pdm.lock file yields several requests all using the correct authentication:
- 200 - /api/pypi/&lt;my-repo>/**simple**/foo-bar/
- 200 - /api/pypi/&lt;my-repo>/foo_bar-1.1b1-py3-none-any.whl
- 200 - /api/pypi/&lt;my-repo>/foo_bar-1.1.dev2-py3-none-any.whl
- 304 - /api/pypi/&lt;my-repo>/foo_bar-1.1.dev2-py3-none-any.whl

`pdm install` with a pdm.lock file yields the following request twice and the installation fails:
- 403 /api/pypi/&lt;my-repo>/foo_bar-1.1.dev2-py3-none-any.whl

I suspect the following:
- the installation without lock file queries the package information using authentication and then reuses the same authentication information for downloading the wheels.
- the installation with the lock file does not need to query package information so no request is made to the package index with the suffix `/simple`. The download is then executed without authentication.

**Comment by frostming** [comment] 2023-03-06 12:41
> * the installation with the lock file does not need to query package information so no request is made to the package index with the suffix `/simple`. The download is then executed without authentication.

Partially correct, PDM will search for the indexes to find the credentials from the matching index: https://github.com/pdm-project/pdm/blob/f6cc4ebc385ba0f2c640c3ceda0024faac3835c7/src/pdm/models/auth.py#L32-L42

**Comment by frostming** [comment] 2023-03-08 07:05
Hi, @noirbizarre @michaelze any chance verify if #1759 fixes the issue? The issue fixes a case the auth can't be found from the **default**(pypi) source.

**Comment by michaelze** [comment] 2023-03-08 13:22
I applied the patch from #1759 to my local installation of pdm but did notice any difference (pdm install without pdm.lock file works, with lock file does not work).
However, in the linked discussion, another form of providing credentials is mentioned whereas I followed the one specified in the documentation (https://pdm.fming.dev/latest/usage/project/#hide-the-credentials-from-pyprojecttoml).
I also tried providing "<username>:<password>" (verbatim) before the hostname part of the url which causes pdm to prompt for my username/password during manual installation (if -v is used). I did not succeed to provide the username/password using this method when the build is execute without user interaction (e.g. CI build).

Any Suggestions? I'm also willing to contribute to the documentation as soon as we come up with a working solution.

**Comment by michaelze** [comment] 2023-04-11 18:54
I finally had the time to further debug this issue. The culprit seems to be the mirror I have defined for pypi as an additional source which is also hosted on the same domain but does not require authentication (hence the source URL does not have any auth info).

When installing without a `pdm.lock` file, querying my index source with auth provided for packages causes the credentials to be cached in the auth object for the `netloc`. When the packages are downloaded later down the road, the credentials are already cached and everything is fine.
When installing with a lock file, I guess, no index is queried and the packages are downloaded directly. Now when unearth receives a 401, it tries to determine the credentials and ultimately iterates the sources in the pyproject.toml file. As my first source (the mirror for pypi.org) does not have any credentials but matches the `netloc`, it returns `None` for the auth (https://github.com/frostming/unearth/blob/e457237c9aef7b4df20e1655651b4fd5d0b5c0c8/src/unearth/auth.py#L170).

That means, I can work around this issue by defining credentials for the pypi mirror even if it does not need any but the next person might have a similar problem.

What are your thoughts on this?

**Comment by michaelze** [comment] 2023-04-12 05:52
Basically, yes. We are using Artifactory for the PyPi Mirror as well as for our internal packages.

**Comment by frostming** [comment] 2023-04-13 01:57
Then I think [using keyring] could help in your case.

[using keyring](https://pdm.fming.dev/latest/usage/config/#index-configuration-merging:~:text=If%20the%20index%20requires%20a%20username%20and%20password%2C%20but%20they%20can%27t%20be%20found%20from%20the%20environment%20variables%20nor%20config%20file%2C%20PDM%20will%20prompt%20you%20to%20enter%20them.%20Or%2C%20if%20keyring%20is%20installed%2C%20it%20will%20be%20used%20as%20the%20credential%20store.%20PDM%20can%20use%20the%20keyring%20from%20either%20the%20installed%20package%20or%20the%20CLI.)

Closing this as there is nothing more we could do here.

**Closed by frostming** 2023-04-13 01:57 UTC
Labels: bug, not enough info
