### ISSUE TITLE
`pdm sync --dry-run` does not show all package changes that `pdm sync` will perform

### ISSUE THREAD

**Issue by hcoohb** [pdm-project/pdm#862] opened 2022-01-20 05:12 UTC
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

- Initialize pdm package `pdm init` and `pdm add scipy`
- Manually edit the `pyproject.toml` and add "numpy==1.16.5" as dependency (forcing a change of numpy version)
- Running `pdm lock`. The pdm.lock file is correctly modified
- Run `pdm sync --dry-run`

## Actual behavior

The only output is 
```
Packages to update:
```

## Expected behavior

What should be displayed is the change in numpy version, as this will correctly happen if we run `pdm sync`
```
Packages to update:
  - numpy 1.21.1 -> 1.16.5
```

Surprisingly, running `pdm sync --dry-run -v` gives the correct output!
## Environment Information

```bash
pdm info:
PDM version:        1.12.6
Python Interpreter: C:/Users/Me/AppData/Local/Programs/Python/Python37/python.EXE (3.7)
Project Root:       C:/Users/Me/Devel/test
Project Packages:   C:\Users\Me\Devel\test\__pypackages__\3.7

pdm info --env:
{
  "implementation_name": "cpython",
  "implementation_version": "3.7.5",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19041",
  "python_full_version": "3.7.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.7",
  "sys_platform": "win32"
}
```

**Comment by frostming** [comment] 2022-01-20 05:48
Sorry, but I can't reproduce. Not sure if it has anything to do with platform or Python version.

**Comment by hcoohb** [comment] 2022-01-21 01:01
It might be platform dependent indeed. I just tried with other python version and I have the same behavior

**Comment by frostming** [comment] 2022-02-16 10:04
Not enough info to reproduce the issue, closing it.

**Closed** 2022-02-16 10:04 UTC
Labels: bug
