### ISSUE TITLE
Docker build error, library not loaded.

### ISSUE THREAD

**Issue by robml** [pdm-project/pdm#897] opened 2022-02-08 22:01 UTC
## Is your feature request related to a problem? Please describe.

I was trying to replicate step 1-3 of the official [Docker](https://docs.docker.com/samples/django/) tutorial, namely this part here:
```
# syntax=docker/dockerfile:1
FROM python:3
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/
```
and adapt it for PDM. I had already "added" via `pdm` Django and the `requests` library. The docker-compose.yml file creates effectively 2 services: a web and a database one (standard for Django I feel). However after the build only the `db` service runs while the `web` one fails, and the logs should the following message:
`ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?`

## Describe the solution you'd like

Is there a way to replicate the above for `pdm` instead of a multi-stage build. I know it is best practice but for learning purposes I am taking it slowly with the above first. I tried the following:
```
# syntax=docker/dockerfile:1
FROM python:3
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY pyproject.toml pdm.lock /code/
RUN pip install pdm && pdm install --prod --no-lock --no-editable
COPY . /code/
```
but as mentioned this lead to Django not being found/loaded. Any ideas how to go about this?

**Comment by pawamoy** [comment] 2022-02-08 22:36
For reference, discussion happening at https://github.com/pdm-project/pdm/discussions/896

**Comment by frostming** [comment] 2022-02-11 03:14
Not a bug of PDM, closing this.

**Closed by frostming** 2022-02-11 03:14 UTC
Labels: enhancement
