### ISSUE TITLE
Requirements export with VCS dependencies

### ISSUE THREAD

**Issue by aryadovoy** [pdm-project/pdm#1842] opened 2023-04-19 04:51 UTC
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```shell
pdm add "git+https://github.com/username/private-repo.git@master"
pdm export -f requirements --prod --without-hashes -o requirements.txt 
```

## Actual behavior

Real URL was changed to URL from docs.

```shell
The exported requirements file is no longer cross-platform. Using it on other platforms may cause unexpected result.
STATUS: Resolving packages from lockfile...
Traceback (most recent call last):
  File "/home/aryadovoy/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/aryadovoy/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 255, in main
    return Core().main(args)
           ^^^^^^^^^^^^^^^^^
  File "/home/aryadovoy/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 193, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/home/aryadovoy/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 188, in main
    self.handle(project, options)
  File "/home/aryadovoy/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 154, in handle
    command.handle(project, options)
  File "/home/aryadovoy/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/cli/commands/export.py", line 68, in handle
    candidates = resolve_candidates_from_lockfile(project, requirements.values())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryadovoy/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/cli/actions.py", line 140, in resolve_candidates_from_lockfile
    mapping, *_ = resolve(
                  ^^^^^^^^
  File "/home/aryadovoy/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/resolver/core.py", line 35, in resolve
    result = resolver.resolve(requirements, max_rounds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryadovoy/.local/share/pdm/venv/lib/python3.11/site-packages/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryadovoy/.local/share/pdm/venv/lib/python3.11/site-packages/resolvelib/resolvers.py", line 426, in resolve
    name = min(unsatisfied_names, key=self._get_preference)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryadovoy/.local/share/pdm/venv/lib/python3.11/site-packages/resolvelib/resolvers.py", line 203, in _get_preference
    return self._p.get_preference(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryadovoy/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/resolver/providers.py", line 84, in get_preference
    is_backtrack_cause = any(dep.identify() in backtrack_identifiers for dep in self.get_dependencies(candidate))
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryadovoy/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/resolver/providers.py", line 176, in get_dependencies
    deps, requires_python, _ = self.repository.get_dependencies(candidate)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryadovoy/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/models/repositories.py", line 82, in get_dependencies
    requirements, requires_python, summary = getter(candidate)
                                             ^^^^^^^^^^^^^^^^^
  File "/home/aryadovoy/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/models/repositories.py", line 418, in _get_dependencies_from_lockfile
    return self.candidate_info[self._identify_candidate(candidate)]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: ('private-repo', None, 'git+https://github.com/username/private-repo.git', False)
```

## Expected behavior

After requirements export should be created what contains something like this:

```text
-e git+https://github.com/username/private-repo.git@master#egg=appello-logger
```

## Environment Information

```bash
PDM version:
  2.5.2
Python Interpreter:
  /home/aryadovoy/Documents/code/tmp/test_for_logger/.venv/bin/python (3.11)
Project Root:
  /home/aryadovoy/Documents/code/tmp/test_for_logger
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.2",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.0.12-100.fc35.x86_64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Thu Dec 8 16:53:55 UTC 2022",
  "python_full_version": "3.11.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

**Comment by aryadovoy** [comment] 2023-04-19 05:05
It wast ok after `pdm update -d`.

**Comment by frostming** [comment] 2023-04-19 05:07
Ok, so i guess it might be caused by a malformed lockfile. Closing this now.

**Closed by frostming** 2023-04-19 05:07 UTC
Labels: bug
