### ISSUE TITLE
Error executing Jupyter command 'lab': [Errno 8] Exec format error

### ISSUE THREAD

**Issue by steve-marmalade** [pdm-project/pdm#494] opened 2021-06-02 17:18 UTC
- [x] I have searched the issue tracker and believe that this is not a duplicate.

```
$ pdm run -v jupyter lab

Traceback (most recent call last):
  File "/usr/local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/pdm/1.6.2/libexec/lib/python3.9/site-packages/pdm/core.py", line 184, in main
    return Core().main(args)
  File "/usr/local/Cellar/pdm/1.6.2/libexec/lib/python3.9/site-packages/pdm/core.py", line 145, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/usr/local/Cellar/pdm/1.6.2/libexec/lib/python3.9/site-packages/pdm/core.py", line 140, in main
    f(options.project, options)
  File "/usr/local/Cellar/pdm/1.6.2/libexec/lib/python3.9/site-packages/pdm/cli/commands/run.py", line 199, in handle
    self._run_command(
  File "/usr/local/Cellar/pdm/1.6.2/libexec/lib/python3.9/site-packages/pdm/cli/commands/run.py", line 99, in _run_command
    os.execv(expanded_command, expanded_args)
OSError: [Errno 8] Exec format error
```

Note that I get the same error when running:

```bash
$ ./__pypackages__/3.9/bin/jupyter lab
Error executing Jupyter command 'lab': [Errno 8] Exec format error
```

## Steps to reproduce

```bash
pdm init
pdm add --dev jupyterlab
```

## Actual behavior

Unable to launch Jupyter Lab

## Expected behavior

Expected to be able to launch Jupyter Lab

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

pdm info && pdm info --env
PDM version:        1.6.2
Python Interpreter: /Users/steve/.pyenv/shims/python (3.9)
Project Root:       /Users/steve/code/storeleads-data
Project Packages:   /Users/steve/code/storeleads-data/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.4",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "20.4.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64",
  "python_full_version": "3.9.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}
```

**Comment by jeffreyc** [comment] 2021-07-09 05:09
I just encountered this issue with scrapy (`pdm run scrapy ...`) using pyenv. Reconfiguring PDM to use a different interpreter (e.g., Python installed via Homebrew) resolves this issue.

I believe the issue is related to the shebang in the scripts created py PDM (e.g., `__pypackages__/3.9/bin/scrapy`) when PDM is configured to use a Python that is a script instead of an executable (e.g., `.pyenv/shims/python`) and PDM's `os.execv` call (e.g., `os.execv('.../__pypackages__/3.9/bin/scrapy', ['.../__pypackages__/3.9/bin/scrapy', ...])`), which raises "OSError: [Errno 8] Exec format error" in that case.

This can be fixed by editing the script to change the shebang to use `/usr/bin/env python` or to change the `os.execv` call to invoke the Python interpreter instead of the script directly (e.g., `os.execv(sys.executable, [sys.executable] + ['.../__pypackages__/3.9/bin/scrapy', ...])`). I'm not sure which would be preferred in this case.

**Comment by frostming** [comment] 2021-07-09 07:58
@jeffreyc Sounds reasonable, thanks for investigation. Would like to submit a PR?

**Comment by jeffreyc** [comment] 2021-07-10 03:04
I just submitted a PR to invoke the Python interpreter instead of the script. Please feel free to request changes if you'd prefer a different approach.

**Closed** 2022-01-20 02:48 UTC
Labels: bug
