### ISSUE TITLE
pdm add --no-build-isolation failed in nfs

### ISSUE THREAD

**Issue by fancyerii** [pdm-project/pdm#2686] opened 2024-03-13 06:45 UTC
I want to install [flash-atten](https://github.com/Dao-AILab/flash-attention). When I config pdm to nfs, it fails. But when I use default disk. it will ok. Here are the steps to reproduce.

1. config pdm

ubuntu@VM-4-12-ubuntu:/nas/lili/codes/pt/flashattnpdm$ cat ~/.config/pdm/config.toml 

```toml
cache_dir = "/nas/lili/codes/pt/.cache/pdm"

[install]
cache = true
cache_method = "symlink_individual"

[global_project]
path = "/nas/lili/codes/pt/.config/pdm/global-project"

[venv]
location = "/nas/lili/codes/pt/.local/share/pdm/venvs"
```

/nas is nfs mount point.

then run "pdm add flash-attn --no-isolation", it failed:

```
ubuntu@VM-4-12-ubuntu:/nas/lili/codes/pt/flashattnpdm$ pdm add flash-attn --no-isolation
Adding packages to default dependencies: flash-attn
🔒 Lock successful
Changes are written to pyproject.toml.
Synchronizing working set with resolved packages: 26 to add, 0 to update, 0 to remove   

  ✔ Install filelock 3.13.1 successful
  ✔ Install einops 0.7.0 successful
  ✔ Install jinja2 3.1.3 successful
  ✔ Install fsspec 2024.2.0 successful
  ✔ Install markupsafe 2.1.5 successful
  ✔ Install ninja 1.11.1.1 successful
  ✔ Install mpmath 1.3.0 successful
  ✔ Install nvidia-cuda-runtime-cu12 12.1.105 successful
  ✔ Install nvidia-cuda-cupti-cu12 12.1.105 successful
  ✔ Install nvidia-cuda-nvrtc-cu12 12.1.105 successful
  ✔ Install nvidia-curand-cu12 10.3.2.106 successful
  ✔ Install networkx 3.2.1 successful
  ✖ Install flash-attn 2.5.6 failed
  ✔ Install nvidia-nvtx-cu12 12.1.105 successful
  ✔ Install packaging 24.0 successful
  ✔ Install nvidia-nvjitlink-cu12 12.4.99 successful
  ✔ Install nvidia-cufft-cu12 11.0.2.54 successful
  ✔ Install nvidia-cusolver-cu12 11.4.5.107 successful
  ✔ Install typing-extensions 4.10.0 successful
  ✔ Install nvidia-cusparse-cu12 12.1.0.106 successful
  ✔ Install nvidia-nccl-cu12 2.19.3 successful
  ✔ Install triton 2.2.0 successful
  ✔ Install nvidia-cublas-cu12 12.1.3.1 successful
  ✔ Install sympy 1.12 successful
  ✔ Install nvidia-cudnn-cu12 8.9.2.26 successful
  ✔ Install torch 2.2.1 successful
Retry failed jobs
  ✖ Install flash-attn 2.5.6 failed

ERRORS:
add flash-attn failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 285, in install_candidate
    self.manager.install(can)
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/manager.py", line 34, in install
    dist_info = installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/candidates.py", line 418, in build
    self.wheel = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))  
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/builders/wheel.py", line 28, in build
    filename = self._hook.build_wheel(out_dir, config_settings, metadata_directory)
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pyproject_hooks/_impl.py", line 209, in build_wheel
    return self._call_hook('build_wheel', {
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/builders/base.py", line 261, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/builders/base.py", line 107, in log_subprocessor
    raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
  opt = self.warn_dash_deprecation(opt, section)


torch.__version__  = 2.2.1+cu121


running bdist_wheel
Guessing wheel URL:
https://github.com/Dao-AILab/flash-attention/releases/download/v2.5.6/flash_attn-2.5.6+cu122torch2.2cxx11abiFALSE-cp39-cp39-linux_x86_64.whl
Raw wheel path
/nas/lili/codes/pt/.cache/pdm/wheels/c2/28/cf/4d5781d537c5af694d260f8272a7ff79aa8cfe35da44a505ab/.tmp-2ovnws91/flash_attn-2.5.6-cp39-cp39-lin
ux_x86_64.whl
error: [Errno 18] Invalid cross-device link: 'flash_attn-2.5.6+cu122torch2.2cxx11abiFALSE-cp39-cp39-linux_x86_64.whl' ->
'/nas/lili/codes/pt/.cache/pdm/wheels/c2/28/cf/4d5781d537c5af694d260f8272a7ff79aa8cfe35da44a505ab/.tmp-2ovnws91/flash_attn-2.5.6-cp39-cp39-li
nux_x86_64.whl'

See /tmp/pdm-install-faq7r_8j.log for detailed debug log.
``` 

this line is critical:

```
Invalid cross-device link: 'flash_attn-2.5.6+cu122torch2.2cxx11abiFALSE-cp39-cp39-linux_x86_64.whl' ->
'/nas/lili/codes/pt/.cache/pdm/wheels/c2/28/cf/4d5781d537c5af694d260f8272a7ff79aa8cfe35da44a505ab/.tmp-2ovnws91/flash_attn-2.5.6-cp39-cp39-li
nux_x86_64.whl'
```
I think pdm want to create link from nfs to main disk.

2. use main disk
```
mv /home/ubuntu/.config/pdm/config.toml ~/.config/pdm/config.toml.bak
mkdir ~/pdmtest && cd ~/pdmtest
ubuntu@VM-4-12-ubuntu:~/pdmtest$ pdm add flash-attn --no-isolation
```

it is ok.

3. remove --no-isolation

```
ubuntu@VM-4-12-ubuntu:/nas/lili/codes/pt/flashattnpdm$ pdm add flash-attn
Adding packages to default dependencies: flash-attn
🔒 Lock successful
Changes are written to pyproject.toml.
Synchronizing working set with resolved packages: 1 to add, 0 to update, 0 to remove

  ✖ Install flash-attn 2.5.6 failed
Retry failed jobs
  ✖ Install flash-attn 2.5.6 failed

ERRORS:
add flash-attn failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 285, in install_candidate
    self.manager.install(can)
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/manager.py", line 34, in install
    dist_info = installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/candidates.py", line 418, in build
    self.wheel = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/builders/wheel.py", line 26, in build
    requires = self._hook.get_requires_for_build_wheel(config_settings)
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/builders/base.py", line 261, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/builders/base.py", line 107, in log_subprocessor
    raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Module 'packaging' is missing, please make sure it is specified in the
'build-system.requires' section. If it is not possible, add it to the project and use '--no-isolation' option.
Showing the last 10 lines of the build output:
  File "/tmp/pdm-build-env-loe455r2-shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/tmp/pdm-build-env-loe455r2-shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
    self.run_setup()
  File "/tmp/pdm-build-env-loe455r2-shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 487, in run_setup
    super().run_setup(setup_script=setup_script)
  File "/tmp/pdm-build-env-loe455r2-shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 9, in <module>
ModuleNotFoundError: No module named 'packaging'

See /tmp/pdm-install-_06aq3tc.log for detailed debug log.
[InstallationError]: Some package operations are not complete yet
WARNING: Add '-v' to see the detailed traceback
```

**Comment by pawamoy** [comment] 2024-03-13 10:14
Without build isolation, it does not work indeed because flash-atten requires `packaging` to be built, but doesn't declare `packaging` in its build requirements (only its install requirements). Even if it did, it would also have to defer the `packaging` imports (currently it can easily defer `packaging.parse` which is only used in function, but not `packaging.Version` which is used at the module level).

With build isolation, the package builds correctly (I suppose you have `packaging` available in the your environment), but then you activated the install cache feature with symlinks while installing onto a drive that does not support cross-drive symlinks: that cannot work. You have three options IIUC:

- disable install cache
- change the install cache method
- change the location of your global project

**Comment by fancyerii** [comment] 2024-03-14 02:47
> pdm add flash-attn --no-isolation

disable install cache can't solve the problem.

```shell
ubuntu@VM-4-12-ubuntu:/nas/lili/codes/pt/flashattnpdm$ pdm config
Site/default configuration (/etc/xdg/pdm/config.toml):
build_isolation = True
cache_dir = /home/ubuntu/.cache/pdm
check_update = True
global_project.fallback = False
global_project.fallback_verbose = True
global_project.path = /home/ubuntu/.config/pdm/global-project
global_project.user_site = False
install.cache = False
install.cache_method = symlink
install.parallel = True
pypi.ignore_stored_index = False
pypi.json_api = False
pypi.url = https://pypi.org/simple
pypi.verify_ssl = True
python.providers = ['venv', 'path', 'asdf', 'pyenv', 'rye', 'winreg', 'macos']
python.use_pyenv = True
python.use_venv = True
strategy.inherit_metadata = True
strategy.resolve_max_rounds = 10000
strategy.save = minimum
strategy.update = reuse
theme.error = red
theme.info = blue
theme.primary = cyan
theme.req = bold green
theme.success = green
theme.warning = yellow
venv.backend = virtualenv
venv.in_project = True
venv.location = /home/ubuntu/.local/share/pdm/venvs
venv.prompt = {project_name}-{python_version}
venv.with_pip = False

Home configuration (/home/ubuntu/.config/pdm/config.toml):
cache_dir = /nas/lili/codes/pt/.cache/pdm
global_project.path = /nas/lili/codes/pt/.config/pdm/global-project
install.cache = True
install.cache_method = symlink_individual
venv.location = /nas/lili/codes/pt/.local/share/pdm/venvs

Project configuration (/nas/lili/codes/pt/flashattnpdm/pdm.toml):
install.cache = False

```

```shell
ubuntu@VM-4-12-ubuntu:/nas/lili/codes/pt/flashattnpdm$ pdm add flash-attn --no-isolation
ERRORS:
add flash-attn failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 285, in install_candidate
    self.manager.install(can)
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/manager.py", line 34, in install
    dist_info = installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/candidates.py", line 418, in build
    self.wheel = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/builders/wheel.py", line 28, in build
    filename = self._hook.build_wheel(out_dir, config_settings, metadata_directory)
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pyproject_hooks/_impl.py", line 209, in build_wheel
    return self._call_hook('build_wheel', {
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/builders/base.py", line 261, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/builders/base.py", line 107, in log_subprocessor
    raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
  opt = self.warn_dash_deprecation(opt, section)


torch.__version__  = 2.2.1+cu121


running bdist_wheel
Guessing wheel URL:
https://github.com/Dao-AILab/flash-attention/releases/download/v2.5.6/flash_attn-2.5.6+cu122torch2.2cxx11abiFALSE-cp39-cp39-linux_x86_64.whl
Raw wheel path
/nas/lili/codes/pt/.cache/pdm/wheels/c2/28/cf/4d5781d537c5af694d260f8272a7ff79aa8cfe35da44a505ab/.tmp-4n8bfeqj/flash_attn-2.5.6-cp39-cp39-lin
ux_x86_64.whl
error: [Errno 18] Invalid cross-device link: 'flash_attn-2.5.6+cu122torch2.2cxx11abiFALSE-cp39-cp39-linux_x86_64.whl' ->
'/nas/lili/codes/pt/.cache/pdm/wheels/c2/28/cf/4d5781d537c5af694d260f8272a7ff79aa8cfe35da44a505ab/.tmp-4n8bfeqj/flash_attn-2.5.6-cp39-cp39-li
nux_x86_64.whl'

See /tmp/pdm-install-kh1dcney.log for detailed debug log.
[InstallationError]: Some package operations are not complete yet
WARNING: Add '-v' to see the detailed traceback

```

It's the same link problem. I don't find where  flash_attn-2.5.6+cu122torch2.2cxx11abiFALSE-cp39-cp39-linux_x86_64.whl is. Maybe it build this whl in a temp directory in main disk(I just guess becuase I can't find it. Then it try to link it to nfs.

**Comment by fancyerii** [comment] 2024-03-14 02:48
> Without build isolation, it does not work indeed because flash-atten requires `packaging` to be built, but doesn't declare `packaging` in its build requirements (only its install requirements). Even if it did, it would also have to defer the `packaging` imports (currently it can easily defer `packaging.parse` which is only used in function, but not `packaging.Version` which is used at the module level).
> 
> With build isolation, the package builds correctly (I suppose you have `packaging` available in the your environment), but then you activated the install cache feature with symlinks while apparently installing into a different device than the cache directory. You have three options IIUC:
> 
> * disable install cache
> * change the install cache method
> * change the location of the cache or the project

disable install cache can't solve the problem.

```shell
ubuntu@VM-4-12-ubuntu:/nas/lili/codes/pt/flashattnpdm$ pdm config
Site/default configuration (/etc/xdg/pdm/config.toml):
build_isolation = True
cache_dir = /home/ubuntu/.cache/pdm
check_update = True
global_project.fallback = False
global_project.fallback_verbose = True
global_project.path = /home/ubuntu/.config/pdm/global-project
global_project.user_site = False
install.cache = False
install.cache_method = symlink
install.parallel = True
pypi.ignore_stored_index = False
pypi.json_api = False
pypi.url = https://pypi.org/simple
pypi.verify_ssl = True
python.providers = ['venv', 'path', 'asdf', 'pyenv', 'rye', 'winreg', 'macos']
python.use_pyenv = True
python.use_venv = True
strategy.inherit_metadata = True
strategy.resolve_max_rounds = 10000
strategy.save = minimum
strategy.update = reuse
theme.error = red
theme.info = blue
theme.primary = cyan
theme.req = bold green
theme.success = green
theme.warning = yellow
venv.backend = virtualenv
venv.in_project = True
venv.location = /home/ubuntu/.local/share/pdm/venvs
venv.prompt = {project_name}-{python_version}
venv.with_pip = False

Home configuration (/home/ubuntu/.config/pdm/config.toml):
cache_dir = /nas/lili/codes/pt/.cache/pdm
global_project.path = /nas/lili/codes/pt/.config/pdm/global-project
install.cache = True
install.cache_method = symlink_individual
venv.location = /nas/lili/codes/pt/.local/share/pdm/venvs

Project configuration (/nas/lili/codes/pt/flashattnpdm/pdm.toml):
install.cache = False

```

```shell
ubuntu@VM-4-12-ubuntu:/nas/lili/codes/pt/flashattnpdm$ pdm add flash-attn --no-isolation
ERRORS:
add flash-attn failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 285, in install_candidate
    self.manager.install(can)
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/manager.py", line 34, in install
    dist_info = installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/candidates.py", line 418, in build
    self.wheel = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/builders/wheel.py", line 28, in build
    filename = self._hook.build_wheel(out_dir, config_settings, metadata_directory)
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pyproject_hooks/_impl.py", line 209, in build_wheel
    return self._call_hook('build_wheel', {
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/builders/base.py", line 261, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/builders/base.py", line 107, in log_subprocessor
    raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
  opt = self.warn_dash_deprecation(opt, section)


torch.__version__  = 2.2.1+cu121


running bdist_wheel
Guessing wheel URL:
https://github.com/Dao-AILab/flash-attention/releases/download/v2.5.6/flash_attn-2.5.6+cu122torch2.2cxx11abiFALSE-cp39-cp39-linux_x86_64.whl
Raw wheel path
/nas/lili/codes/pt/.cache/pdm/wheels/c2/28/cf/4d5781d537c5af694d260f8272a7ff79aa8cfe35da44a505ab/.tmp-4n8bfeqj/flash_attn-2.5.6-cp39-cp39-lin
ux_x86_64.whl
error: [Errno 18] Invalid cross-device link: 'flash_attn-2.5.6+cu122torch2.2cxx11abiFALSE-cp39-cp39-linux_x86_64.whl' ->
'/nas/lili/codes/pt/.cache/pdm/wheels/c2/28/cf/4d5781d537c5af694d260f8272a7ff79aa8cfe35da44a505ab/.tmp-4n8bfeqj/flash_attn-2.5.6-cp39-cp39-li
nux_x86_64.whl'

See /tmp/pdm-install-kh1dcney.log for detailed debug log.
[InstallationError]: Some package operations are not complete yet
WARNING: Add '-v' to see the detailed traceback

```

It's the same link problem. I don't find where  flash_attn-2.5.6+cu122torch2.2cxx11abiFALSE-cp39-cp39-linux_x86_64.whl is. Maybe it build this whl in a temp directory in main disk(I just guess becuase I can't find it. Then it try to link it to nfs.

**Comment by fancyerii** [comment] 2024-03-14 02:52
> Without build isolation, it does not work indeed because flash-atten requires `packaging` to be built, but doesn't declare `packaging` in its build requirements (only its install requirements). Even if it did, it would also have to defer the `packaging` imports (currently it can easily defer `packaging.parse` which is only used in function, but not `packaging.Version` which is used at the module level).
> 
> With build isolation, the package builds correctly (I suppose you have `packaging` available in the your environment), but then you activated the install cache feature with symlinks while apparently installing into a different device than the cache directory. You have three options IIUC:
> 
> * disable install cache
> * change the install cache method
> * change the location of the cache or the project

I haven't try other install cache method because if disabling install cache failed, it will fail too. 
Changing the location of the cache to main disk(not nfs) works. As I stated in original post. That's why I think it's a bug related to nfs.

**Comment by frostming** [comment] 2024-03-14 10:07
So the library you installed doesn't allow to link from nfs(yeah it isn't even reported by PDM)
You should use isolated build after disabling install.cache.

Not a bug of PDM, closing it now.

**Closed by frostming** 2024-03-14 10:07 UTC

**Comment by pawamoy** [comment] 2024-03-14 10:31
I'm not sure exactly what's wrong, but as @frostming points out it's likely an issue with your environment and NFS mount points.  From what you posted it looks like there's only one mount point but the error says "cross-device"... Maybe NFS just does not allow symlink's :shrug:

**Comment by vickianand** [comment] 2024-06-17 02:23
@pawamoy , were you able to resolve this? if so, what did you do?
I am also facing similar error as you when running `pdm add flash-attn --no-isolation`. Although I am not even using nfs.
