### ISSUE TITLE
respect-source-order not working as expected

### ISSUE THREAD

**Issue by ralbertazzi** [pdm-project/pdm#1746] opened 2023-03-01 14:56 UTC
- [x] I have searched the issue tracker and believe that this is not a duplicate.

According to the documentation, the `respect-source-order` parameter is used in case one `may want to return packages from the preferred source, and search for others if they are missing from the former source`. However, by checking HTTP calls it looks like PDM is searching in the secondary (private) repository even if a match is found on the primary pypi repository. 

## Steps to reproduce

Run `pdm install` on this `pyproject.toml`:

```toml
[project]
authors = [{ name = "Riccardo Albertazzi", email = "ra@bendingspoons.com" }]
dependencies = [
    "requests>=2.28.2",
    "numpy>=1.24.1",
    "pandas>=1.5.3",
    "fastapi>=0.89.1",
    "gunicorn>=20.1.0",
    "psutil>=5.9.4",
    "pydantic>=1.10.4",
    "streamlit>=1.17.0",
    "uvicorn>=0.20.0",
    "aio-pika>=8.3.0",
    "aioredis>=2.0.1",
    "tenacity>=8.1.0",
    "pillow>=9.4.0",
    "google-cloud-storage>=2.7.0",
    "google-cloud-bigquery>=3.4.2",
    "google-cloud-compute>=1.10.0",
    "bsp-vault>=6.0.0",
]
description = ""
license = { text = "MIT" }
name = ""
requires-python = ">=3.11,<4.0"
version = ""

[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "black>=22.12.0",
    "mypy>=0.991",
    "isort>=5.11.4",
    "pylint>=2.15.10",
    "flake8>=6.0.0",
    "ruff>=0.0.231",
    "responses>=0.22.0",
]

# I tried explicitly setting pypi as the first source defined in the TOML. This didn't change the behaviour
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[[tool.pdm.source]]
name = "bendingspoons"
url = "https://${ARTIFACTORY_USERNAME}:${ARTIFACTORY_ACCESS_TOKEN}@bendingspoons.jfrog.io/bendingspoons/api/pypi/pypi/simple"
verify_ssl = true

[tool.pdm.resolution]
respect-source-order = true
```

## Actual behavior

This is the result of hard-forcing debug logs during the dependency resolution. The output is related to a single library but all of them perform the same. As you can see pdm calls the simple API of the private repo even though it first called the pypi simple API and got a result.
```bash
2023-03-01 15:52:50,217 INFO       Adding requirement mypy>=0.991
2023-03-01 15:52:50,218 DEBUG    Collecting links from https://pypi.org/simple/mypy/
2023-03-01 15:52:50,218 DEBUG    Found index url https://pypi.org/simple
2023-03-01 15:52:50,218 DEBUG    Looking up "https://pypi.org/simple/mypy/" in the cache
2023-03-01 15:52:50,218 DEBUG    Request header has "max_age" as 0, cache bypassed
2023-03-01 15:52:50,219 DEBUG    Starting new HTTPS connection (1): pypi.org:443
2023-03-01 15:52:50,269 DEBUG    https://pypi.org:443 "GET /simple/mypy/ HTTP/1.1" 304 0
2023-03-01 15:52:50,272 DEBUG    Fetching HTML page https://pypi.org/simple/mypy/ (from cache)
2023-03-01 15:52:50,299 DEBUG    Collecting links from https://***@bendingspoons.jfrog.io/bendingspoons/api/pypi/pypi/simple/mypy/
2023-03-01 15:52:50,300 DEBUG    Found credentials in url for bendingspoons.jfrog.io
2023-03-01 15:52:50,300 DEBUG    Looking up "https://bendingspoons.jfrog.io/bendingspoons/api/pypi/pypi/simple/mypy/" in the cache
2023-03-01 15:52:50,300 DEBUG    Request header has "max_age" as 0, cache bypassed
2023-03-01 15:52:50,300 DEBUG    No cache entry available
2023-03-01 15:52:50,300 DEBUG    Starting new HTTPS connection (1): bendingspoons.jfrog.io:443
2023-03-01 15:52:50,891 DEBUG    https://bendingspoons.jfrog.io:443 "GET /bendingspoons/api/pypi/pypi/simple/mypy/ HTTP/1.1" 200 None
2023-03-01 15:52:51,450 DEBUG    Updating cache with response from "https://bendingspoons.jfrog.io/bendingspoons/api/pypi/pypi/simple/mypy/"
2023-03-01 15:52:51,452 DEBUG    Fetching HTML page https://***@bendingspoons.jfrog.io/bendingspoons/api/pypi/pypi/simple/mypy/
2023-03-01 15:52:51,545 DEBUG    	Found matching candidates:
2023-03-01 15:52:51,545 DEBUG    	  <Candidate mypy@1.0.1 from https://pypi.org/simple/mypy/>
2023-03-01 15:52:51,545 DEBUG    	  <Candidate mypy@1.0.0 from https://pypi.org/simple/mypy/>
2023-03-01 15:52:51,545 DEBUG    	  <Candidate mypy@0.991 from https://pypi.org/simple/mypy/>
2023-03-01 15:52:51,545 DEBUG    	  <Candidate mypy@1.0.1 from https://bendingspoons.jfrog.io/bendingspoons/api/pypi/pypi/simple/mypy/>
2023-03-01 15:52:51,545 DEBUG    	  <Candidate mypy@1.0.0 from https://bendingspoons.jfrog.io/bendingspoons/api/pypi/pypi/simple/mypy/>
2023-03-01 15:52:51,545 DEBUG    	  <Candidate mypy@0.991 from https://bendingspoons.jfrog.io/bendingspoons/api/pypi/pypi/simple/mypy/>
```

## Expected behavior

When a match on pypi is found, pdm should not call the simple API of the private secondary repository. This is particularly important in my case as the API of Artifactory looks an order of magnitude slower than the one of PyPI, making the whole dependency resolution process quite slow.

## Environment Information

```bash
PDM version:
  2.4.5
Python Interpreter:
  /Users/ra/projects/pdm-test/.venv/bin/python (3.11)
Project Root:
  /Users/ra/projects/pdm-test
Project Packages:
  None

PDM 2.4.5 is installed, while 2.4.6 is available.
Please run `pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.1",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "21.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000",
  "python_full_version": "3.11.1",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}

PDM 2.4.5 is installed, while 2.4.6 is available.
Please run `pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.
```

**Comment by ralbertazzi** [comment] 2023-03-01 16:29
I believe https://github.com/pdm-project/pdm/issues/1645 would also be of help, assuming that once you specify a direct package->index mapping the same package won't be searched in other repositories

**Comment by frostming** [comment] 2023-03-02 01:59
Duplicate of #1509

**Closed by frostming** 2023-03-02 01:59 UTC
Labels: bug
