### ISSUE TITLE
`pdm plugin remove` is not working

### ISSUE THREAD

**Issue by xanterx** [pdm-project/pdm#935] opened 2022-02-24 05:13 UTC
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

```bash
❯ pdm plugin remove pdm-venv -v
Traceback (most recent call last):
  File "/Users/_/Library/Python/3.10/bin/pdm", line 10, in <module>
    sys.exit(main())
  File "/Users/_/Library/Application Support/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 233, in main
    return Core().main(args)
  File "/Users/_/Library/Application Support/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 168, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/Users/_/Library/Application Support/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 163, in main
    f(options.project, options)
  File "/Users/_/Library/Application Support/pdm/venv/lib/python3.10/site-packages/pdm/cli/commands/plugin.py", line 167, in handle
    packages_to_remove = self._resolve_dependencies_to_remove(valid_packages)
  File "/Users/_/Library/Application Support/pdm/venv/lib/python3.10/site-packages/pdm/cli/commands/plugin.py", line 142, in _resolve_dependencies_to_remove
    ws = WorkingSet()
  File "/Users/_/Library/Application Support/pdm/venv/lib/python3.10/site-packages/pdm/models/working_set.py", line 79, in __init__
    self._dist_map = {
  File "/Users/_/Library/Application Support/pdm/venv/lib/python3.10/site-packages/pdm/models/working_set.py", line 80, in <dictcomp>
    normalize_name(dist.metadata["Name"]): dist
  File "/Users/_/Library/Application Support/pdm/venv/lib/python3.10/site-packages/pdm/utils.py", line 487, in normalize_name
    return re.sub(r"[^A-Za-z0-9.]+", "-", name).lower()
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

## Actual behavior

Failing to remove plugin

## Expected behavior

Should remove the plugin

## Environment Information

```bash
PDM version:        1.13.2
Python Interpreter: /Users/_/demo_project/.venv/bin/python (3.10)
Project Root:       /Users/_/demo_project
Project Packages:   None
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.1",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "20.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 20.6.0: Wed Jan 12 22:22:42 PST 2022; root:xnu-7195.141.19~2/RELEASE_X86_64",
  "python_full_version": "3.10.1",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment] 2022-02-24 06:36
Can't reproduce, maybe your `pdm-venv` installation is broken.

**Comment by xanterx** [comment] 2022-02-24 15:35
Tested it with `pdm-packer` also but got the same error. I will try to dig deep on this and will share more details on it.

For removing the plugin I had to go to the pdm installation venv and remove it from there manually via pip, which worked perfectly.

**Comment by frostming** [comment] 2022-06-17 10:47
Close this issue due to lack of reproducing information.

**Closed by frostming** 2022-06-17 10:47 UTC
Labels: bug
