### ISSUE TITLE
Segmentation faults happens occasionally in Github actions CI

### ISSUE THREAD

**Issue by Viicos** [pdm-project/pdm#3165] opened 2024-09-17 08:16 UTC
We are facing occasional CI failures on Github. Here is an example:

https://github.com/pydantic/pydantic/actions/runs/10898138750/job/30240806893?pr=10421

Sorry I can't provide more info. I don't have time to debug this. Feel free to close.

**Comment by frostming** [comment] 2024-09-18 00:24
May be a duplicate of #2940

**Closed by frostming** 2024-09-18 00:24 UTC
Labels: 🐛 bug
