### ISSUE TITLE
PDM fails to install dependencies in Docker image

### ISSUE THREAD

**Issue by ioliiva** [pdm-project/pdm#1621] opened 2023-01-14 01:22 UTC
- [x] I have searched the issue tracker and believe that this is not a duplicate.

I have a project that I migrated from Poetry to PDM.
I install all the dependencies in my local environment (without Docker) and it works perfectly but when I dockerize the application and try to install the dependencies it fails.

**Both in my local environment and in the Docker image I use Python 3.9.16**

## Steps to reproduce

In the root of the project I execute the following command:
`$ pdm install -d --no-editable -G jupyter`

## Actual behavior

```
$ pdm install -d --no-editable -G jupyter -v
STATUS: Resolving packages from lockfile...
[RequirementError]: Invalid marker: Expected a marker variable or quoted string
    ; sys_platform == "win32"
    ^
```
The stack trace is as follows:
```
$ pdm install -d --no-editable -G jupyter
See /tmp/pdm-install-resolve-6t5vfq90.log for detailed debug log.
[RequirementError]: Invalid marker: Expected a marker variable or quoted string
    ; sys_platform == "win32"
    ^
root@16235a3663e1:/home/app# cat /tmp/pdm-install-resolve-6t5vfq90.log
pdm.termui: Error occurs
Traceback (most recent call last):
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/termui.py", line 240, in logging
    yield logger
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 141, in resolve_candidates_from_lockfile
    mapping, *_ = resolve(
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/resolver/core.py", line 35, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/resolvelib/resolvers.py", line 521, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/resolvelib/resolvers.py", line 402, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/resolvelib/resolvers.py", line 238, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/resolvelib/resolvers.py", line 228, in _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/resolver/providers.py", line 189, in get_dependencies
    deps, requires_python, _ = self.repository.get_dependencies(candidate)
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/repositories.py", line 91, in get_dependencies
    reqs.append(parse_requirement(line))
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/requirements.py", line 483, in parse_requirement
    r = FileRequirement.create(**m.groupdict())
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/requirements.py", line 272, in create
    return super().create(**kwargs)  # type: ignore
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/requirements.py", line 147, in create
    raise RequirementError("Invalid marker: %s" % str(e)) from None
pdm.exceptions.RequirementError: Invalid marker: Expected a marker variable or quoted string
    ; sys_platform == "win32"
    ^
```

## Expected behavior

```
$ pdm install -d --no-editable -G jupyter
All packages are synced to date, nothing to do.
Installing the project as a package...
  ✔ Update api 0.1.0 -> 0.1.0 successful

🎉 All complete!
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.4.0
Python Interpreter:
  /opt/.venv/bin/python (3.9)
Project Root:
  /home/app
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.16",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.0.18-300.fc37.x86_64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Sat Jan 7 17:10:00 UTC 2023",
  "python_full_version": "3.9.16",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}

```

**Comment by frostming** [comment] 2023-01-14 03:14
Please provide your `pyproject.toml` or I don't know what dependencies it is trying to install.

**Comment by ioliiva** [comment] 2023-01-14 03:25
> Please provide your `pyproject.toml` or I don't know what dependencies it is trying to install.

Sure. I attach pyproject.toml file.

**Remove the .txt extension at the end**

[pyproject.toml.txt](https://github.com/pdm-project/pdm/files/10416459/pyproject.toml.txt)

**Comment by frostming** [comment] 2023-01-18 08:59
It is caused by a dependency of `uvicorn`: `"colorama>=0.4.*; sys_platform == \"win32\"",`, the cause is the same as #1619 . Closing it for duplicate.

I don't know how you bootstrap `pdm` but for now, as a workaround, you can downgrade the `packaging` to `<22`.

**Closed** 2023-01-18 08:59 UTC
Labels: bug, not enough info
