### ISSUE TITLE
Import Poetry requirement list constraints

### ISSUE THREAD

**Issue by s0undt3ch** [pdm-project/pdm#448] opened 2021-05-07 05:16 UTC
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```
pdm import -f poetry ~/path/to/project/pyproject.toml -v
```

Offending entry in `pyproject.toml`
```toml
pyzmq = [
  {version = ">=17.0.0", python = "<3.9"},
  {version = ">=19.0.2", python = ">=3.9"},
  {version = "<=20.0.0", python = "<3.6"}
]
```

## Actual behavior

```
Traceback (most recent call last):
  File "/tmp/.venv/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/tmp/.venv/lib/python3.7/site-packages/pdm/core.py", line 184, in main
    return Core().main(args)
  File "/tmp/.venv/lib/python3.7/site-packages/pdm/core.py", line 145, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/tmp/.venv/lib/python3.7/site-packages/pdm/core.py", line 140, in main
    f(options.project, options)
  File "/tmp/.venv/lib/python3.7/site-packages/pdm/cli/commands/import_cmd.py", line 35, in handle
    do_import(project, options.filename, options.format, options)
  File "/tmp/.venv/lib/python3.7/site-packages/pdm/cli/actions.py", line 485, in do_import
    project_data, settings = FORMATS[key].convert(project, filename, options)
  File "/tmp/.venv/lib/python3.7/site-packages/pdm/formats/poetry.py", line 208, in convert
    return converter.convert()
  File "/tmp/.venv/lib/python3.7/site-packages/pdm/formats/base.py", line 60, in convert
    self._data[key] = func(self, value)
  File "/tmp/.venv/lib/python3.7/site-packages/pdm/formats/poetry.py", line 140, in dependencies
    req = _convert_req(key, req_dict)
  File "/tmp/.venv/lib/python3.7/site-packages/pdm/formats/poetry.py", line 71, in _convert_req
    assert isinstance(req_dict, str)
AssertionError
```

## Expected behavior

Handle the dependency constraints list

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.5.2
Python Interpreter: /tmp/.venv/bin/python (3.7)
Project Root:       /tmp/.venv/proj
Project Packages:   /tmp/.venv/proj/__pypackages__/3.7
{
  "implementation_name": "cpython",
  "implementation_version": "3.7.7",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.11.16-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT Wed, 21 Apr 2021 17:22:13 +0000",
  "python_full_version": "3.7.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.7",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment] 2021-05-07 06:20
PDM do not has that ability of specifying the same dependency with different version set and markers #46 , even if you imported it successfully it won't work as you expect. So the best way is to revise the dependency table to make them importable into PDM.

**Comment by s0undt3ch** [comment] 2021-05-07 06:55
Some versions are just not available on different python versions(which pdm might handle) or even platforms(because we want wheel packages, not source packages).
It's kind of a show stopper for pdm not to be able to handle these.
Any background as to why it was chosen not to support this?

**Comment by frostming** [comment] 2021-05-07 10:01
It is restricted by the resolver [resolvelib](https://github.com/sarugaku/resolvelib) and I recommend you report it there.

To be brief, the resolver requires an identifier for each requirement to so that it know whether the results from two requirements should be merged. When it comes to multiversion requirements, given their sub-dependencies may or may not have different versions, it is hard to tell whether the results should be merged. And it requires to determine whether two environment markers are mutually exclusive. Think of these examples:
1. 
```
A==1; os_name=="nt"
A==2; python_version=="3.8"
```
Should this be resolved correctly?

2.
```
A==1; python_version=="3.7"
A==2; python_version=="3.8"
1)both A1 and A2 depends on B==1
2)A1 -> B1, A2->B2
```
Which versions of B should be pinned in the lockfile?

I am not saying this is impossible, it just needs more effort and design to make them work correctly. And it is not supported by resolvelib

**Comment by frostming** [comment] 2021-05-07 12:48
```toml
[tool.poetry.dependencies]
python = "^2.7||^3.6"
pytest = [
    {version = "==4.6.*", python="<=2.7"},
    {version = ">=5", python=">2.7"}
]
```
Poetry lock fails with this dependency set.

**Comment by s0undt3ch** [comment] 2021-05-07 17:29
And the exported requirements.txt
```
pytest==4.6.11; python_version <= "2.7"
pytest==6.2.4; python_version >= "3.6"
```

**Comment by s0undt3ch** [comment] 2021-05-07 17:31
```
[tool.poetry.dependencies]
python = "^2.7||^3.6"

[tool.poetry.dev-dependencies]
pytest = [
    {version = ">=4.6.0,<5.0.0", python="<=2.7"},
    {version = ">=5.0.0", python=">=3.6"}
]
```
Also works

**Comment by frostming** [comment] 2021-05-10 02:42
Close this for a duplicate of #46

**Closed by frostming** 2021-05-10 02:42 UTC
Labels: bug
