### ISSUE TITLE
`__pypackages__/.gitignore` not ignored

### ISSUE THREAD

**Issue by branchvincent** [pdm-project/pdm#667] opened 2021-10-04 03:53 UTC
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```
pdm init -n
pdm install
git init && git add --all && git commit -m init
git ls-files
```

## Actual behavior

```console
$ git ls-files
.pdm.toml
__pypackages__/.gitignore
pdm.lock
pyproject.toml
```

## Expected behavior

For `__pypackages__` to be completely ignored, as with [`pytest`](https://github.com/pytest-dev/pytest/blob/828fde1156ba87e3f2d3850ffc64a3f4d9455ebd/src/_pytest/cacheprovider.py#L211) and [`mypy`](https://github.com/python/mypy/blob/c90026bd867635a4efe70cdacf0caaf00a986914/mypy/build.py#L1131-L1132)

```diff 
.pdm.toml
- __pypackages__/.gitignore
pdm.lock
pyproject.toml
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.8.5                                                                                   
Python Interpreter: /usr/local/opt/python@3.9/bin/python3.9 (3.9)                                           
Project Root:       /private/var/folders/wr/gcv7765n6v3118gtwtyr8x9r0000gn/T/tmp.zH36TMht                   
Project Packages:   /private/var/folders/wr/gcv7765n6v3118gtwtyr8x9r0000gn/T/tmp.zH36TMht/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.7",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "20.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64",
  "python_full_version": "3.9.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}
```

Relates to #446

**Comment by frostming** [comment] 2021-10-05 02:03
Not a bug, close it now.

**Closed by frostming** 2021-10-05 02:03 UTC
Labels: bug
