### ISSUE TITLE
After successful installation, pdm install fails if certain dependencies installed

### ISSUE THREAD

**Issue by edible-programs** [pdm-project/pdm#1596] opened 2023-01-03 19:13 UTC
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

`pdm add accelerate` then `pdm install` afterwards

## Actual behavior

```bash
pdm.termui: Error occurs
Traceback (most recent call last):
  File "/home/_/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/termui.py", line 227, in logging
    yield logger
  File "/home/_/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/actions.py", line 139, in resolve_candidates_from_lockfile
    mapping, *_ = resolve(
  File "/home/_/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/resolver/core.py", line 35, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/home/_/.local/share/pdm/venv/lib/python3.10/site-packages/resolvelib/resolvers.py", line 521, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/_/.local/share/pdm/venv/lib/python3.10/site-packages/resolvelib/resolvers.py", line 372, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/_/.local/share/pdm/venv/lib/python3.10/site-packages/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/home/_/.local/share/pdm/venv/lib/python3.10/site-packages/resolvelib/structs.py", line 127, in __bool__
    next(iter(self))
  File "/home/_/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/resolver/providers.py", line 151, in <genexpr>
    return (
  File "/home/_/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/repositories.py", line 493, in find_candidates
    for key in self._matching_keys(requirement):
  File "/home/_/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/repositories.py", line 477, in _matching_keys
    if can_req.path != getattr(requirement, "path", None):  # type: ignore
AttributeError: 'NamedRequirement' object has no attribute 'path'
```
## Expected behavior

```
All packages are synced to date, nothing to do.

🎉 All complete!
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

PDM version:
  2.3.4
Python Interpreter:
  /usr/bin/python3.10 (3.10)
Project Root:
  /home/_/Documents/<project>
Project Packages:
  /home/_/Documents/<project>/__pypackages__/3.10
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.7",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.79.1-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Wed Nov 23 01:01:46 UTC 2022",
  "python_full_version": "3.10.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
```

**Comment by edible-programs** [comment] 2023-01-03 19:25
When I print the `requirement` variable, I get an empty byte string `b''`. Strange,

**Comment by edible-programs** [comment] 2023-01-03 20:30
Unable to reproduce when installing pdm using `pip3.10 install --user pdm`

**Comment by Lawouach** [comment] 2023-01-09 08:19
Hello,

I suddenly started to get the same issue on my GH action yesterday. Bizarre thing is that two hours before that the action was fine. I have no idea what changed.

```
Run pdm install -v -d --no-lock
  pdm install -v -d --no-lock
  shell: /usr/bin/bash -e {0}
  env:
    PR_NUMBER: 
    PYTHONPATH: /home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/pep58[2](https://github.com/XXXX/XXXX/actions/runs/3871928642/jobs/6600190682#step:5:2)
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/XXXX/XXXX/actions/runs/3871928642/jobs/6600190682#step:5:3).11.1/x6[4](https://github.com/XXXX/XXXX/actions/runs/3871928642/jobs/6600190682#step:5:4)
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.1/x[6](https://github.com/XXXX/XXXX/actions/runs/3871928642/jobs/6600190682#step:5:6)4/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.1/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.1/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.1/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.1/x64/lib
    LD_PRELOAD: /lib/x[8](https://github.com/XXXX/XXXX/actions/runs/3871928642/jobs/6600190682#step:5:8)6_64-linux-gnu/libgcc_s.so.1

python.use_venv is on, creating a virtualenv for this project...
Run command: ['/home/runner/.local/share/pdm/venv/bin/python', '-m', 'virtualenv', '.venv', '-p', '/opt/hostedtoolcache/Python/3.11.1/x64/bin/python', '--no-pip', '--no-setuptools', '--no-wheel', '--prompt=backend-3.11']
created virtual environment CPython3.11.1.final.0-64 in 128ms
  creator CPython3Posix(dest=.venv, clear=False, no_vcs_ignore=False, global=False)
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
Virtualenv is created successfully at .venv
Traceback (most recent call last):
  File "/home/runner/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 259, in main
    return Core().main(args)
  File "/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 191, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 186, in main
    f(project, options)
  File "/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/commands/install.py", line 62, in handle
    actions.do_sync(
  File "/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/actions.py", line 196, in do_sync
    candidates = resolve_candidates_from_lockfile(project, requirements)
  File "/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/actions.py", line 139, in resolve_candidates_from_lockfile
    mapping, *_ = resolve(
  File "/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/resolver/core.py", line 35, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/resolvelib/resolvers.py", line 521, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/resolvelib/resolvers.py", line 402, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/resolvelib/resolvers.py", line 238, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/resolvelib/resolvers.py", line 229, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/resolvelib/structs.py", line 127, in __bool__
    next(iter(self))
  File "/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/resolver/providers.py", line [15](https://github.com/XXXX/XXXX/actions/runs/3871928642/jobs/6600190682#step:5:16)1, in <genexpr>
    return (
  File "/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/repositories.py", line 493, in find_candidates
    for key in self._matching_keys(requirement):
  File "/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/repositories.py", line [47](https://github.com/XXXX/XXXX/actions/runs/3871928642/jobs/6600190682#step:5:48)7, in _matching_keys
    if can_req.path != getattr(requirement, "path", None):  # type: ignore
AttributeError: 'NamedRequirement' object has no attribute 'path'
Error: Process completed with exit code 1.
```

**Comment by Lawouach** [comment] 2023-01-09 09:32
I managed to drill down to this package being responsible for the problem: https://github.com/Colin-b/pytest_httpx

Luckily I don't need it so I was able to skip it entirely but it may be useful for investigation.

**Comment by frostming** [comment] 2023-01-09 10:30
This is because of the release of [packaging 23.0](https://pypi.org/project/packaging/23.0/), some specifiers are no longer considered valid according to the new rules. Unfortunately, this is a deliberate choice, not a bug so we will follow the new rules.

**Comment by Lawouach** [comment] 2023-01-09 10:39
Right. Thanks for the heads up.

**Comment by edible-programs** [comment] 2023-01-14 01:29
> This is because of the release of [packaging 23.0](https://pypi.org/project/packaging/23.0/), some specifiers are no longer considered valid according to the new rules. Unfortunately, this is a deliberate choice, not a bug so we will follow the new rules.

It also fails to parse local version specifiers, which as far as I can tell have not been deprecated. This is causing an error when I try to add "torch>=1.12.1+cu116" as a dependency. If this is indeed a bug, could packaging 21.3 be downgraded in the interim?

**Comment by frostming** [comment] 2023-01-14 03:39
> This is causing an error when I try to add "torch>=1.12.1+cu116" as a dependency

Local versions shouldn't appear in a comparison specifier, using `torch>=1.12.1` would be fine. If it is generated by PDM then it should be a bug, but I don't think it is because we have fixed this issue recently.

**Comment by edible-programs** [comment] 2023-01-14 23:21
Got it, thank you.

**Comment by tvboxme** [comment] 2023-01-18 02:46
> This is because of the release of [packaging 23.0](https://pypi.org/project/packaging/23.0/), some specifiers are no longer considered valid according to the new rules. Unfortunately, this is a deliberate choice, not a bug so we will follow the new rules.

However, this is too surprising, can we add a warning here?

**Comment by frostming** [comment] 2023-01-18 02:48
Duplicate of #1619, closing this to avoid distraction.

**Closed by frostming** 2023-01-18 02:48 UTC
Labels: bug

**Comment by frostming** [comment] 2023-01-18 02:49
> > This is because of the release of [packaging 23.0](https://pypi.org/project/packaging/23.0/), some specifiers are no longer considered valid according to the new rules. Unfortunately, this is a deliberate choice, not a bug so we will follow the new rules.
> 
> However, this is too surprising, can we add a warning here?

Indeed this should be an error rather than a warning because it can't pass through.
