### ISSUE TITLE
Can't shutdown `sphinx-autobuild` server when running through `pdm run`

### ISSUE THREAD

**Issue by ShaiAvr** [pdm-project/pdm#2345] opened 2023-10-29 10:36 UTC
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

I recently started to use `pdm` to manage my project, and I ran into an issue when trying to use `sphinx-autobuild` to automatically build and serve my documentation. When I run the `sphinx-autobuild` command using `pdm run` (since it's installed in the virtual environment), the first time works just fine: The documentation is built, the server starts, I can browse my docs and at the end *shut down the server by pressing `Ctrl+C` in the terminal*. However, I then run the same command again to spawn the server again. The server works just fine, but when I try to shut it down with `Ctrl+C`, it doesn't work. The shortcut doesn't do anything, and I am forced to shut down the server by closing the terminal and killing the `sphinx-autobuild` process with the task manager (I am on Windows 11, and it seems `sphinx-autobuild` spawns a server process that keeps working after I kill the terminal).

After investigating a bit, I found this bug only happens when using `pdm run`. If I activate the virtual environment (with `Invoke-Expression (pdm venv activate)` for PowerShell on Windows) and run `sphinx-autobuild` without `pdm run`, it works fine as many times as I want. I can start the server, shut it down with `Ctrl+C`, start it again, and shut it down again with `Ctrl+C` and there are no issues.

## Steps to reproduce

Create a `pdm` managed project, and install `sphinx` and `sphinx-autobuild` as dependencies (or dev-dependencies). Create a simple documentation site with `pdm run sphinx-quickstart docs` (I chose to separate source and build directories, but I don't think it matters for this bug). Run `pdm run sphinx-autobuild ./docs/source/ ./docs/build/html --watch ./src/` (I needed it to watch for changes in the src directory too, but I don't think it's related to this bug). The first time works fine: The docs are built, the server is up, you can open the docs in a browser, and *you can shut down the server with `Ctrl+C`*. After shutting down the server, run this command again to start another server. The server works fine and you can open the browser and see the docs, but *you can't shut down the server*. `Ctrl+C` doesn't do anything and you have to kill the process instead.

Note that activating the virtual environment (with `Invoke-Expression (pdm venv activate)` for PowerShell on Windows) and running the server `sphinx-autobuild ./docs/source/ ./docs/build/html --watch ./src/` without `pdm run` works fine. You can shut down the server and restart it as many times as you want.

## Actual behavior

The second time I run the server, the `Ctrl+C` shortcut no longer shuts it down and I am forced to manually kill the process.

## Expected behavior

I can use `Ctrl+C` to shut down the server without any issues.

## Environment Information
Windows 11 Pro
Version	22H2
OS build	22621.2428

Python 3.11.5 and pdm 2.10.0

```bash
# Paste the output of `pdm info && pdm info --env` below:

PDM version:
  2.10.0
Python Interpreter:
  D:\dev\python\pdm-demo\.venv\Scripts\python.exe (3.11)
Project Root:
  D:/dev/python/pdm-demo
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.5",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.22621",
  "python_full_version": "3.11.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "win32"
}
```

**Comment by xzmeng** [comment] 2023-10-29 14:15
It is the same as https://github.com/pdm-project/pdm/issues/2292

**Comment by pawamoy** [comment] 2023-10-29 15:05
Thanks for the link @xzmeng, we will close this as duplicate of #2292 then, since a solution is suggested there.

**Closed by pawamoy** 2023-10-29 15:05 UTC
Labels: 🐛 bug
