### ISSUE TITLE
Interactive update

### ISSUE THREAD

**Issue by patrick91** [pdm-project/pdm#1588] opened 2022-12-28 12:48 UTC
Hi there! Big fan of the project, I was wondering if you'd consider implementing an interactive update feature, similar to yarn's upgrade interactive feature, which looks like this:

```
[1/? Choose which packages to update. (Press <space> to select, <a> to toggle all, <i> to inverse s
election)
 devDependencies
❯◯ autoprefixer      6.7.7  ❯  7.0.0          https://github.com/postcss/autoprefixer#readme
 ◯ webpack           2.4.1  ❯  2.5.1          https://github.com/webpack/webpack

 dependencies
 ◯ bull              2.2.6  ❯  3.0.0-alpha.3  https://github.com/OptimalBits/bull#readme
 ◯ fs-extra          3.0.0  ❯  3.0.1          https://github.com/jprichardson/node-fs-extra
 ◯ socket.io         1.7.3  ❯  1.7.4          https://github.com/socketio/socket.io#readme
 ◯ socket.io-client  1.7.3  ❯  1.7.4          https://github.com/Automattic/socket.io-client#readme
```

Reference: https://classic.yarnpkg.com/lang/en/docs/cli/upgrade-interactive/

**Comment by pawamoy** [comment] 2022-12-28 23:04
This is probably a good candidate for a plugin :)

**Comment by patrick91** [comment] 2022-12-28 23:28
@pawamoy why not! and maybe if it becomes optional it could be built-in too 😊

I don't have time now to try and build it, but if I do, I'll update the issue 😊 If there's anyone who wants to try, feel free to do it 😊

**Comment by frostming** [comment] 2022-12-28 23:56
Yes, it better fits in a plugin, because that may require a TUI library for the selection.

**Comment by frostming** [comment] 2023-01-03 07:51
Closing it for now because we are not going to support it in the main project.

**Closed by frostming** 2023-01-03 07:51 UTC
Labels: enhancement

**Comment by q0w** [comment] 2023-01-03 13:03
The problem is that do_update and do_lock are doing lots of work, so adding interactive menu requires to copy-paste all code just to add several lines

**Comment by q0w** [comment] 2023-01-03 19:56
I tried to implement the basic update-interactive (using a pre-lock signal and rewriting frame locals.). You could try using `pip install pdm-update-interactive` https://github.com/q0w/pdm-update-interactive/  What do you think?
