### ISSUE TITLE
KeyAlreadyPresent]: Key "name " already exists.

### ISSUE THREAD

**Issue by mburaksayici** [pdm-project/pdm#1000] opened 2022-03-26 13:49 UTC
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
pdm install after pulling.

## Actual behavior
Installing packages without problem after pulling the code that includes pyproject.toml.

```bash
(base) $ pdm install -v
Traceback (most recent call last):
  File "/home/azureuser/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/azureuser/.local/share/pdm/venv/lib/python3.7/site-packages/pdm/core.py", line 233, in main
    return Core().main(args)
  File "/home/azureuser/.local/share/pdm/venv/lib/python3.7/site-packages/pdm/core.py", line 168, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/azureuser/.local/share/pdm/venv/lib/python3.7/site-packages/pdm/core.py", line 163, in main
    f(options.project, options)
  File "/home/azureuser/.local/share/pdm/venv/lib/python3.7/site-packages/pdm/cli/commands/install.py", line 38, in handle
    strategy = actions.check_lockfile(project, False)
  File "/home/azureuser/.local/share/pdm/venv/lib/python3.7/site-packages/pdm/cli/actions.py", line 137, in check_lockfile
    elif not project.is_lockfile_compatible():
  File "/home/azureuser/.local/share/pdm/venv/lib/python3.7/site-packages/pdm/project/core.py", line 478, in is_lockfile_compatible
    self.lockfile.get("metadata", {}).get("lock_version", "")
  File "/home/azureuser/.local/share/pdm/venv/lib/python3.7/site-packages/pdm/project/core.py", line 141, in lockfile
    data = tomlkit.parse(self.lockfile_file.read_text("utf-8"))
  File "/home/azureuser/.local/share/pdm/venv/lib/python3.7/site-packages/tomlkit/api.py", line 82, in parse
    return Parser(string).parse()
  File "/home/azureuser/.local/share/pdm/venv/lib/python3.7/site-packages/tomlkit/parser.py", line 154, in parse
    key, value = self._parse_table()
  File "/home/azureuser/.local/share/pdm/venv/lib/python3.7/site-packages/tomlkit/parser.py", line 1025, in _parse_table
    result = self._parse_aot(result, full_key)
  File "/home/azureuser/.local/share/pdm/venv/lib/python3.7/site-packages/tomlkit/parser.py", line 1066, in _parse_aot
    _, table = self._parse_table(name_first)
  File "/home/azureuser/.local/share/pdm/venv/lib/python3.7/site-packages/tomlkit/parser.py", line 993, in _parse_table
    table.raw_append(_key, item)
  File "/home/azureuser/.local/share/pdm/venv/lib/python3.7/site-packages/tomlkit/items.py", line 1366, in raw_append
    self._value.append(key, _item)
  File "/home/azureuser/.local/share/pdm/venv/lib/python3.7/site-packages/tomlkit/container.py", line 265, in append
    raise KeyAlreadyPresent(key)
tomlkit.exceptions.KeyAlreadyPresent: Key "name " already exists.


```

## Expected behavior
pdm install doesnt work when i pull the code from github, and it should i believe. 
Also, I have always having troubles when i try to delete/reinstall pdm. I also don't know what should be the correct way of doing it. When I have troubles with pdm, at least i would like to reinstall and run it again, but it's also causing other problems.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

PDM version:        1.13.5
Python Interpreter: /usr/bin/python3.8 (3.8)
Project Root:       /home/azureuser/**
Project Packages:   /home/azureuser/**/__pypackages__/3.8
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.10",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.11.0-1028-azure",
  "platform_system": "Linux",
  "platform_version": "#31~20.04.2-Ubuntu SMP Tue Jan 18 08:46:15 UTC 2022",
  "python_full_version": "3.8.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}

```

**Comment by frostming** [comment] 2022-03-27 09:25
The lock file may be malformed, can you paste the content of `pdm.lock`?

**Comment by frostming** [comment] 2022-06-17 10:46
This issue is not valid due to lack of reproducing information, close it now.

**Closed** 2022-06-17 10:45 UTC
Labels: bug, not enough info
