### ISSUE TITLE
`dev-dependencies` are not being added to `pyproject.toml` when `tool.pdm.source` is present.

### ISSUE THREAD

**Issue by nikhilweee** [pdm-project/pdm#2639] opened 2024-02-19 17:25 UTC
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. Start a new project by running `pdm init`. You can choose to stick with the defaults.
2. Edit the generated `pyproject.toml` file to add the following entry

```toml
[[tool.pdm.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cpu"
```

3. Try to add a dev dependency such as `pdm add -d flask`

## Actual behavior

You will get the following message:
```console
Ignoring non-existing groups: dev
```
`flask` will not be added to `pyproject.toml` 

## Expected behavior

You should get the following message:
```console
Adding packages to dev dev-dependencies: flask
```
`flask` should be added to `pyproject.toml` 
```toml
[tool.pdm.dev-dependencies]
dev = [
    "flask>=3.0.2",
]
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.12.3
Python Interpreter:
  /home/nikhil/miniforge3/envs/project/bin/python (3.12)
Project Root:
  /home/nikhil/projects/project
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.12.1",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.133.1-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Thu Oct 5 21:02:42 UTC 2023",
  "python_full_version": "3.12.1",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment] 2024-02-22 03:14
Can't reproduce, you'd better provide the content of `pyproject.toml` as well.

**Comment by ProfKache** [comment] 2024-04-20 18:14
I have the same issue. I added some packages like django-debug-toolbar in dev dependencies but the pyproject.toml won't update. I actually use the latest version of pdm i.e 2.15.0

**Comment by frostming** [comment] 2024-04-21 10:56
> I have the same issue. I added some packages like django-debug-toolbar in dev dependencies but the pyproject.toml won't update. I actually use the latest version of pdm i.e 2.15.0

I know, but no one provides the content of `pyproject.toml`

**Comment by frostming** [comment] 2024-04-22 06:43
This is inefficient, I decide to close this first, will reopen when reproducible example is given.

**Closed by frostming** 2024-04-22 06:43 UTC
Labels: 🤔 not enough info
