### ISSUE TITLE
Any problem of my project path?

### ISSUE THREAD

**Issue by w-Bro** [pdm-project/pdm#1006] opened 2022-03-30 08:32 UTC
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
Both `pip install pdm` and `(Invoke-WebRequest -Uri https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py -UseBasicParsing).Content | python - ` have been tested on win10 and still got a problem on `init` step.

## Actual behavior

```
D:\test>pdm init -v
Creating a pyproject.toml for PDM...
Traceback (most recent call last):
  File "d:\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Miniconda3\Scripts\pdm.exe\__main__.py", line 7, in <module>
  File "d:\miniconda3\lib\site-packages\pdm\core.py", line 233, in main
    return Core().main(args)
  File "d:\miniconda3\lib\site-packages\pdm\core.py", line 168, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "d:\miniconda3\lib\site-packages\pdm\core.py", line 163, in main
    f(options.project, options)
  File "d:\miniconda3\lib\site-packages\pdm\cli\commands\init.py", line 46, in handle
    actions.do_use(project)
  File "d:\miniconda3\lib\site-packages\pdm\cli\actions.py", line 560, in do_use
    found_interpreters = list(dict.fromkeys(project.find_interpreters(python)))
  File "d:\miniconda3\lib\site-packages\pdm\project\core.py", line 625, in find_interpreters
    for entry in finder.find_all(*args):
  File "d:\miniconda3\lib\site-packages\findpython\finder.py", line 94, in find_all
    matched_python = set(self._find_all_python_versions())
  File "d:\miniconda3\lib\site-packages\findpython\finder.py", line 127, in _find_all_python_versions
    yield from provider.find_pythons()
  File "d:\miniconda3\lib\site-packages\findpython\providers\path.py", line 25, in find_pythons
    yield from self.find_pythons_from_path(path)
  File "d:\miniconda3\lib\site-packages\findpython\providers\base.py", line 41, in find_pythons_from_path
    if not path.is_dir() or not path_is_readable(path):
  File "d:\miniconda3\lib\pathlib.py", line 1358, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "d:\miniconda3\lib\pathlib.py", line 1168, in stat
    return self._accessor.stat(self)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: '"'

D:\test>
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
D:\test>pdm info && pdm info --env
[ProjectError]: The pyproject.toml has not been initialized yet. You can do this by running 'pdm init'.

D:\test>python --version
Python 3.7.4
```

**Comment by frostming** [comment] 2022-03-30 09:23
There is a broken entry `"` in your `PATH` env.

**Comment by w-Bro** [comment] 2022-03-30 10:15
i found the problem, cause by adding a PATH `%JAVA_HOME%\bin;%JAVA_HOME%\jre\bin`, and it shows like  `other\path;"java\home\path\bin;java\home\path\jre\bin"`, it work after i split it. Maybe it could be optimized in the future.

**Comment by frostming** [comment] 2022-03-30 10:57
Closing this cause it is not a bug of PDM(should be fixed upstream)

**Closed by frostming** 2022-03-30 10:57 UTC
Labels: bug
