### ISSUE TITLE
Running python notebook in vscode using a pdm environment

### ISSUE THREAD

**Issue by hcoohb** [pdm-project/pdm#848] opened 2022-01-07 08:26 UTC
First, thanks for providing us with pdm and good documentation, great work!

- [x] I have searched the issue tracker and believe that this is not a duplicate.

It seems we cannot run a jupyter notebook file using the python/notebook extension inside vscode. As vscode is asking for the python interpreter to use, and selecting the main python interpreter does not seem to load the pdm environment. 
we get the error: `Running cells with 'Python 3.7.5 64-bit' requires ipykernel package`

I am not sure it is a bug as such but could not find any mention in the documentation.
Is there a workaround to make the notebook extension recognize the correct environment?
Or is it a limitation of using pep582 and no venv?

(as a side note, running `pdm run jupyter notebook` from terminal allow to run the notebook in the standard jupyter notebook web-based page, but this is not what I need, I need work on the notebook file from vscode directly)
## Steps to reproduce

- Create a new project with pdm pep582 gloabaly and use global cache.
- Add the correct param in .vscode/settings.json so that we can run python script straight from vscode (working).
`pdm add jupyterlab`
- Add a jupyter notebook file that just ouput the version of pandas for example.
in vscode, install the notebook extension and try to open the notebook file inside vscode.

## Actual behavior

Error in vscode notebook viewer, once the interpreter has been selected, it does not see the pdm environment and therefore no ipykernel.

## Expected behavior

A method to specify to vscode notebook extension how to "see" the pdm environment.

## Environment Information

```bash
pdm info:
PDM version:        1.12.1
Python Interpreter: C:/Users/Me/AppData/Local/Programs/Python/Python37/python.EXE (3.7)
Project Root:       C:/Users/Me/Devel/test/jup
Project Packages:   C:\Users\Me\Devel\test\jup\__pypackages__\3.7

pdm info --env:
{
  "implementation_name": "cpython",
  "implementation_version": "3.7.5",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19041",
  "python_full_version": "3.7.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.7",
  "sys_platform": "win32"
}
```

**Comment by frostming** [comment] 2022-01-07 08:30
Did you try https://pdm.fming.dev/#enable-pep-582-globally ?

You may need to restart vscode to see the env change

**Comment by hcoohb** [comment] 2022-01-10 06:58
Yes, I have pep 582 enabled globally, sorry I should have said.
I have no problem running python scripts from vscode terminal that do recognize the pdm environment.
But I cannot run jupyter notebook files inside vscode with the jupyter notebook extension:

![image](https://user-images.githubusercontent.com/12975783/148728138-983b10a1-c3a3-43e0-92bb-5dbf2d44491b.png)

**Comment by hcoohb** [comment] 2022-01-10 07:29
Looking in a bit more details, 
I have the actual output of the step starting the jupyter notebook:
```bash
Info 16:54:39: Cell 0 executed with state Idle
Error 16:54:46: Live Notebook not available for c:\Users\Me\Devel\test\jup\nb.ipynb
Info 16:54:58: Execute Cells request 0
Info 16:54:58: Execute Cell 0 c:\Users\Me\Devel\test\jup\nb.ipynb
Info 16:54:58: Starting Notebook in kernel.ts id = .jvsc74a57bd08793b863be4d44c155d428f69ebfb87deb62a536de2cb61a5666e9f23ee48f8c.C:\Users\Me\AppData\Local\Programs\Python\Python37\python.exe.C:\Users\Me\AppData\Local\Programs\Python\Python37\python.exe.-m#ipykernel_launcher
Info 16:54:58: Creating raw notebook for c:\Users\Me\Devel\test\jup\nb.ipynb
Info 16:54:58: Getting preferred kernel for c:\Users\Me\Devel\test\jup\nb.ipynb
Info 16:54:58: Computing working directory c:\Users\Me\Devel\test\jup\nb.ipynb
Info 16:54:58: Starting raw kernel Python 3.7.5 64-bit
Info 16:54:58: installMissingDependencies ~\AppData\Local\Programs\Python\Python37\python.exe
Info 16:54:58: Process Execution: > ~\AppData\Local\Programs\Python\Python37\python.exe -c "import ipykernel"
> ~\AppData\Local\Programs\Python\Python37\python.exe -c "import ipykernel"
Info 16:54:58: Process Execution: > ~\AppData\Local\Programs\Python\Python37\python.exe -c "import pip"
> ~\AppData\Local\Programs\Python\Python37\python.exe -c "import pip"
Error 16:57:18: Install Missing Dependencies, Class name = k, completed in 140038ms, has a falsy return value, Return Value: undefined [i [Error]: IPyKernel not installed into interpreter Python 3.7.5 64-bit:~\AppData\Local\Programs\Python\Python37\python.exe
	at k.handleKernelDependencyResponse (c:\Users\Me\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:1242890)
	at k.installMissingDependencies (c:\Users\Me\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:1241911)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)] {
  category: 'noipykernel',
  reason: 1
}
Error 16:57:18: Raw session failed to start because dependencies not installed
Error 16:57:18: failed to create INotebook in kernel, UI Disabled = false [i [Error]: IPyKernel not installed into interpreter Python 3.7.5 64-bit:~\AppData\Local\Programs\Python\Python37\python.exe
	at k.handleKernelDependencyResponse (c:\Users\Me\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:1242890)
	at k.installMissingDependencies (c:\Users\Me\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:1241911)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)] {
  category: 'noipykernel',
  reason: 1
}
```

So to me it seems that the correct working directory is set (c:\Users\Me\Devel\test\jup\ is my pdm dir for the project)
But then it seems to fail executing: `~\AppData\Local\Programs\Python\Python37\python.exe -c "import ipykernel"`.
I am confused as executing this in a terminal in the project directory runs without issue...

So would there be a specific settings for the jupyter extension to start python with the pdm environment?

**Comment by frostming** [comment] 2022-01-10 07:39
> So would there be a specific settings for the jupyter extension to start python with the pdm environment?

Might be, the env var `PYTHONPATH` is ignored somehow. But I don't know how to fix it here.

**Comment by hcoohb** [comment] 2022-01-20 05:42
After a bit of investigation, I have found a reliable way of using vscode notebook with a pdm environment (PEP582 global).
I thought I would share as it may help others (and maybe we can add details to the docs?).

So, basically you will just need to create a new ipykernel spec that can be read by VSCODE.
- Create a folder called `PDM_env` inside the folder for ipyernel specs for your system (listed [here](https://jupyter-client.readthedocs.io/en/stable/kernels.html#kernel-specs) - on windows it is `%APPDATA%\jupyter\kernels`)
- Inside create a file called `kernel.json` with the following:
```{
 "argv": [
  "C:\\Users\\USERNAME\\AppData\\Local\\Programs\\Python\\Python37\\python.exe",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "PDM_env",
 "language": "python",
 "env": {"PYTHONPATH": "C:\\Users\\USERNAME\\AppData\\Roaming\\pdm\\venv\\lib\\site-packages\\pdm\\pep582"}
}
```
- Change the python binary path, as well as the path to your global pdm pep582 folder
- Restart vscode and you can now select the kernel "PDM_env" that will load the ipykernel you installed inside the current pdm environment.

This means you only have to create this file once, and then just launch vscode from the folder of the pdm environment.

Another great possibility is to create a virtual env that only contains the ipykernel, that way no need to install it inside the pdm environment we wish to run. we just need to change the kernel.spec to point the python binary path to the one inside our virtual environment. (Although that means we are mixing 2 environments, so package compatibility/versioning might no longer be correct...)

Hope my explanations are clear enough...

**Comment by frostming** [comment] 2022-01-20 05:50
Great, will be good to have it in "Advanced Usage" documentation. Can you make a PR for it?

**Comment by hcoohb** [comment] 2022-01-21 01:33
I'll try to have a go at this next week!

**Comment by bx2** [comment] 2022-02-08 14:53
There is a simpler way to do it. Add a file called `.env` and set your paths there, like so:

```
PYTHONPATH=/your-workspace-path/__pypackages__/<major>.<minor>/lib
```

jupyter notebook reads .env files and sets everything that is needed.

**Comment by frostming** [comment] 2022-02-16 10:05
Nice! Thanks for the solution, I am closing the issue.

**Closed by frostming** 2022-02-16 10:05 UTC
Labels: bug, contribution welcome

**Comment by cye18** [comment] 2022-04-04 20:35
The solution in #988 sometimes works for me, but sometimes doesn't. Here is my environment.

- Installed notebook 6.4.10 using `pdm add notebook`
- Added `PYTHONPATH=/my-project-directory/__pypackages__/3.8/lib` to `.env`

```
$ pdm info && pdm info --env
PDM version:        1.13.6
Python Interpreter: /usr/bin/python3.8 (3.8)
Project Root:       /my-project-directory
Project Packages:  /my-project-directory/__pypackages__/3.8
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.10",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.13.0-1023-gcp",
  "platform_system": "Linux",
  "platform_version": "#28~20.04.1-Ubuntu SMP Wed Mar 30 03:51:07 UTC 2022",
  "python_full_version": "3.8.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}
```

I installed `kfp` and `xgboost` with `pdm add kfp xgboost==1.4.0`. When I import kfp from a jupyter notebook in VSCode, it says `ModuleNotFoundError: No module named 'kfp'`. (The same error for xgboost)

Is the solution in #988 supposed to work in 100% cases? Did I missed anything?

Thanks a lot for your help!

**Comment by cye18** [comment] 2022-04-05 16:22
As I mentioned above, the solution in #988 doesn't always work for me. I found https://github.com/microsoft/vscode-jupyter/issues/5773 that had such discussion as well.

I think the problem is the PYTHONPATH we add to `.env` is not always loaded when the Jupyter Notebook launches. I run `import sys` `print(sys.path)` in the notebook and don't see `/my-project-directory/__pypackages__/3.8/lib`. However, as https://github.com/microsoft/vscode-jupyter/issues/5773#issuecomment-963856204 suggests, if I add PYTHONPATH to `.env` and run `code .`, it will open a new VSCode window in the current directory with the PATH correctly set. I open the same Jupyter Notebook in the new window and run `print(sys.path)` again. `/my-project-directory/__pypackages__/3.8/lib` is there now, and I can import my packages as expected. I think adding `/my-project-directory/__pypackages__/3.8/lib` to the path could work as well if we don't want to opne a new window.

It works for my Ubuntu 20.04 machine. Hopefully it's regardless of OS.
