### ISSUE TITLE
Entrypoint not being installed and wrong version selected by pdm

### ISSUE THREAD

**Issue by lyz-code** [pdm-project/pdm#905] opened 2022-02-11 15:20 UTC
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**
Hey, I'm encountering more weird packaging issues.

## Steps to reproduce

```bash
virtualenv env
source env/bin/activate
pdm init
```

## Actual behavior

First of all, it looks like `pdm add` is not installing the entrypoints:

```
$: pdm add autoimport

Adding packages to default dependencies: autoimport
✔ 🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 10 to add, 0 to update, 0 to remove

  ✔ Install autoflake 1.4 successful
  ✔ Install autoimport 1.0.5 successful
  ✔ Install click 8.0.3 successful
  ✔ Install maison 1.4.0 successful
  ✔ Install pydantic 1.9.0 successful
  ✔ Install pyflakes 2.4.0 successful
  ✔ Install sh 1.14.2 successful
  ✔ Install pyprojroot 0.2.0 successful
  ✔ Install toml 0.10.2 successful
  ✔ Install typing-extensions 4.0.1 successful

🎉 All complete!

$: autoimport --version
zsh: command not found: autoimport

$: pip install autoimport
$: autoimport --version
           autoimport version: 1.2.1
               python version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
                     platform: Linux-4.19.0-5-amd64-x86_64-with-debian-10.11

```

The second issue is that as you can see above the version installed by `pdm` is `1.0.5` which was the last package I made before moving to `pdm`. 

## Expected behavior

`pdm` selects the latest version of the package and the entrypoints are installed when doing `pdm add`

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.12.8
Python Interpreter: /usr/local/bin/python3.9 (3.9)
Project Root:       /tmp/tmp.qI4T7fbAK4
Project Packages:   /tmp/tmp.qI4T7fbAK4/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.8",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "4.19.0-5-amd64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19)",
  "python_full_version": "3.9.8",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}

```

Sorry for being a pain in the ass today :P

**Comment by lyz-code** [comment] 2022-02-11 17:48
I can reproduce the error with `pdm add repository-orm` another package built with the same process

**Comment by frostming** [comment] 2022-02-12 00:37
I can't reproduce with exact the same steps

**Comment by frostming** [comment] 2022-02-12 00:42
Not an issue, `pdm info` is a useful command to debug the environment, closing this.

**Closed by frostming** 2022-02-12 00:42 UTC
Labels: bug

**Comment by lyz-code** [comment] 2022-02-16 11:13
Hey @frostming I've reproduced it without using the PEP 582 path scheme

```
PDM version:        1.12.8
Python Interpreter: /tmp/tmp.rUOtWHTQ8u/env/bin/python3.9 (3.9)
Project Root:       /tmp/tmp.rUOtWHTQ8u
Project Packages:   None
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.10",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "4.19.0-5-amd64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19)",
  "python_full_version": "3.9.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

```bash
$: pdm show autoimport
Name:                  autoimport
Latest version:        1.0.5
Latest stable version: 1.0.5
Summary:               Autoimport missing python libraries.
Author:                Lyz
Author email:          lyz-code-security-advisories@riseup.net
License:               GNU General Public License v3
Homepage:              https://github.com/lyz-code/autoimport
Project URLs:
Platform:              UNKNOWN
Keywords:
```

As you can see the detected version is `1.0.5` while the latest is `1.2.1`, even if you can't reproduce, can you point me on where to start the debugging?

**Comment by frostming** [comment] 2022-02-16 11:28
@lyz-code It is a bug, `pdm show` should not verify `requires-python` value.

**Comment by lyz-code** [comment] 2022-02-16 11:32
Should I open a new issue? or can we reopen this one then

**Comment by frostming** [comment] 2022-02-16 11:39
It is already fixed on the main branch, but okay to file an issue to have a number for it.

**Comment by lyz-code** [comment] 2022-02-16 11:44
If it's fixed then it's ok, I'll wait for the release to check if it works
