### ISSUE TITLE
The scm dynamic version number does not work on windows devices

### ISSUE THREAD

**Issue by InPRTx** [pdm-project/pdm#1896] opened 2023-05-07 15:23 UTC
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce
![image](https://user-images.githubusercontent.com/56180468/236686403-b249ad92-3e05-4197-9610-d9b61ed823ff.png)
![image](https://user-images.githubusercontent.com/56180468/236686368-32a86d58-e03c-4319-bb7c-d37530620876.png)
![image](https://user-images.githubusercontent.com/56180468/236686636-cb5ce82c-ebc8-4314-8c16-3f0b234ef308.png)

## Environment Information
![image](https://user-images.githubusercontent.com/56180468/236686488-81bf995f-b3a1-4a09-9a1a-f513d0ddecf0.png)

**Comment by InPRTx** [comment] 2023-05-07 15:45
And Dynamic file version number is also invalid.
![image](https://user-images.githubusercontent.com/56180468/236687947-d70da0ea-56e3-49a9-8b7b-b9e1b071b76f.png)
![image](https://user-images.githubusercontent.com/56180468/236687891-c7a1d46e-56ef-4840-b473-a4a95d136200.png)

**Comment by frostming** [comment] 2023-05-08 05:11
![image](https://user-images.githubusercontent.com/16336606/236739200-4645b335-f942-407c-8992-1701f175dd89.png)
Can you find out what file it is trying to find? It appears that PDM doesn't have access to the local files.

**Comment by InPRTx** [comment] 2023-05-08 23:02
那个错误是我wsl强制切换成win的错误，它无关紧要，为了避免误会，我再演示win平台不能正常的识别动态文件版本的bug

That error is my forced switch from wsl to win. It doesn’t matter. In order to avoid misunderstanding, I will demonstrate the bug that the win platform cannot normally recognize the dynamic file version.

![image](https://user-images.githubusercontent.com/56180468/236954589-c4c2c855-618b-4879-87ac-2a1751a540b8.png)
![image](https://user-images.githubusercontent.com/56180468/236955601-70207ad1-40a6-42e8-8613-5768772333e5.png)

**Comment by frostming** [comment] 2023-05-10 01:22
Still can't reproduce, can you make the repo public so I can test?

**Comment by InPRTx** [comment] 2023-05-10 03:21
根据你的截图，我补上了这样的内容也正常输出版本号了。或许你们得要在init时候补上这段内容
According to your screenshot, I have added such content and output the version number normally. Maybe you have to add this content during init
```
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
```

**Comment by frostming** [comment] 2023-05-10 03:26
> 根据你的截图，我补上了这样的内容也正常输出版本号了。或许你们得要在init时候补上这段内容 According to your screenshot, I have added such content and output the version number normally. Maybe you have to add this content during init
> 
> ```
> [build-system]
> requires = ["pdm-backend"]
> build-backend = "pdm.backend"
> ```

![image](https://github.com/pdm-project/pdm/assets/16336606/f9de1de1-ad40-4a4b-8aba-4f52350f1d04)

Answer yes to this question and it will be included. Or init with `pdm init --lib`

**Closed by frostming** 2023-05-10 03:26 UTC
Labels: bug
