### ISSUE TITLE
Two tests fail with Python 3.10 (test_set_non_exist_python_path and test_use_python_by_version)

### ISSUE THREAD

**Issue by mcepl** [pdm-project/pdm#865] opened 2022-01-21 12:17 UTC
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

While running the test suite for packaging pdm on openSUSE/Factory (aside from https://github.com/pdm-project/pdm/issues/858) I hit these two failed tests:
```
[ 3213s] =================================== FAILURES ===================================
[ 3213s] ________________________ test_set_non_exist_python_path ________________________
[ 3213s] 
[ 3213s] project_no_init = <Project '/tmp/pytest-of-abuild/pytest-1/test_set_non_exist_python_path0'>
[ 3213s] 
[ 3213s]     def test_set_non_exist_python_path(project_no_init):
[ 3213s]         project_no_init.project_config["python.path"] = "non-exist-python"
[ 3213s]         project_no_init._python = None
[ 3213s] >       assert os.path.normcase(project_no_init.python.executable) == os.path.normcase(
[ 3213s]             sys.executable
[ 3213s]         )
[ 3213s] E       AssertionError: assert '/usr/bin/python3' == '/usr/bin/python3.10'
[ 3213s] E         - /usr/bin/python3.10
[ 3213s] E         ?                 ---
[ 3213s] E         + /usr/bin/python3
[ 3213s] 
[ 3213s] tests/test_project.py:214: AssertionError
[ 3213s] ---------------------------- Captured stdout setup -----------------------------
[ 3213s] Using Python interpreter: /usr/bin/python3.10 (3.10)
[ 3213s] __________________________ test_use_python_by_version __________________________
[ 3213s] 
[ 3213s] project = <Project '/tmp/pytest-of-abuild/pytest-1/test_use_python_by_version0'>
[ 3213s] invoke = <function invoke.<locals>.caller at 0x7f586cc95ea0>
[ 3213s] 
[ 3213s]     def test_use_python_by_version(project, invoke):
[ 3213s]         python_version = ".".join(map(str, sys.version_info[:2]))
[ 3213s]         result = invoke(["use", "-f", python_version], obj=project)
[ 3213s] >       assert result.exit_code == 0
[ 3213s] E       assert 1 == 0
[ 3213s] E         +1
[ 3213s] E         -0
[ 3213s] 
[ 3213s] tests/cli/test_use.py:33: AssertionError
[ 3213s] ---------------------------- Captured stdout setup -----------------------------
[ 3213s] Using Python interpreter: /usr/bin/python3.10 (3.10)
[ 3213s] Changes are written to pyproject.toml.
[ 3213s] =========================== short test summary info ============================
[ 3213s] FAILED tests/test_project.py::test_set_non_exist_python_path - AssertionError...
[ 3213s] FAILED tests/cli/test_use.py::test_use_python_by_version - assert 1 == 0
[ 3213s] ========== 2 failed, 306 passed, 65 deselected in 1560.02s (0:26:00) ===========
```

## Expected behavior

Obviously, all tests should pass.

## Environment Information

Complete information about the environment, all packages used, and steps taken are in the [build log](https://github.com/pdm-project/pdm/files/7913333/_log.txt).

**Comment by mcepl** [comment] 2022-01-21 12:18
Isn’t this:
```diff
---
 tests/test_project.py |    4 +---
 1 file changed, 1 insertion(+), 3 deletions(-)

--- a/tests/test_project.py
+++ b/tests/test_project.py
@@ -211,6 +211,4 @@ def test_global_python_path_config(proje
 def test_set_non_exist_python_path(project_no_init):
     project_no_init.project_config["python.path"] = "non-exist-python"
     project_no_init._python = None
-    assert os.path.normcase(project_no_init.python.executable) == os.path.normcase(
-        sys.executable
-    )
+    assert os.path.normcase(sys.executable).startswith(os.path.normcase(project_no_init.python.executable))
```
solution for the first test?

**Comment by mweinelt** [comment] 2022-01-21 12:39
Fails for us (NixOS) similarly:

```
___________________________ test_find_python_in_path ___________________________
[gw52] linux -- Python 3.9.10 /nix/store/xakdwmwvw3bg43qjn23007dydazjnzx5-python3-3.9.10/bin/python3.9

tmp_path = PosixPath('/build/pytest-of-nixbld/pytest-0/popen-gw52/test_find_python_in_path0')

    def test_find_python_in_path(tmp_path):

        assert (
            utils.find_python_in_path(sys.executable)
            == pathlib.Path(sys.executable).resolve()
        )

        posix_path_to_executable = pathlib.Path(sys.executable).as_posix().lower()
        if sys.platform == "darwin":
            found_version_of_executable = re.split(
                r"(python@[\d.]*\d+)", posix_path_to_executable
            )
            posix_path_to_executable = "".join(found_version_of_executable[0:2])
>       assert (
            utils.find_python_in_path(sys.prefix)
            .as_posix()
            .lower()
            .startswith(posix_path_to_executable)
        )
E       AssertionError: assert False
E        +  where False = <built-in method startswith of str object at 0x7ffff42e06b0>('/nix/store/xakdwmwvw3bg43qjn23007dydazjnzx5-python3-3.9.10/bin/python3.9')
E        +    where <built-in method startswith of str object at 0x7ffff42e06b0> = '/nix/store/xakdwmwvw3bg43qjn23007dydazjnzx5-python3-3.9.10/bin/python'.startswith
E        +      where '/nix/store/xakdwmwvw3bg43qjn23007dydazjnzx5-python3-3.9.10/bin/python' = <built-in method lower of str object at 0x7ffff42e0d30>()
E        +        where <built-in method lower of str object at 0x7ffff42e0d30> = '/nix/store/xakdwmwvw3bg43qjn23007dydazjnzx5-python3-3.9.10/bin/python'.lower
E        +          where '/nix/store/xakdwmwvw3bg43qjn23007dydazjnzx5-python3-3.9.10/bin/python' = <bound method PurePath.as_posix of PosixPath('/nix/store/xakdwmwvw3bg43qjn23007dydazjnzx5-python3-3.9.10/bin/python')>()
E        +            where <bound method PurePath.as_posix of PosixPath('/nix/store/xakdwmwvw3bg43qjn23007dydazjnzx5-python3-3.9.10/bin/python')> = PosixPath('/nix/store/xakdwmwvw3bg43qjn23007dydazjnzx5-python3-3.9.10/bin/python').as_posix
E        +              where PosixPath('/nix/store/xakdwmwvw3bg43qjn23007dydazjnzx5-python3-3.9.10/bin/python') = <function find_python_in_path at 0x7ffff4b9e040>('/nix/store/xakdwmwvw3bg43qjn23007dydazjnzx5-python3-3.9.10')
E        +                where <function find_python_in_path at 0x7ffff4b9e040> = utils.find_python_in_path
E        +                and   '/nix/store/xakdwmwvw3bg43qjn23007dydazjnzx5-python3-3.9.10' = sys.prefix

tests/test_utils.py:66: AssertionError
________________________ test_set_non_exist_python_path ________________________
[gw38] linux -- Python 3.9.10 /nix/store/xakdwmwvw3bg43qjn23007dydazjnzx5-python3-3.9.10/bin/python3.9

project_no_init = <Project '/build/pytest-of-nixbld/pytest-0/popen-gw38/test_set_non_exist_python_path0'>

    def test_set_non_exist_python_path(project_no_init):
        project_no_init.project_config["python.path"] = "non-exist-python"
        project_no_init._python = None
>       assert os.path.normcase(project_no_init.python.executable) == os.path.normcase(
            sys.executable
        )
E       AssertionError: assert '/nix/store/x...10/bin/python' == '/nix/store/x...bin/python3.9'
E         Skipping 58 identical leading characters in diff, use -v to show
E         - /bin/python3.9
E         ?            ---
E         + /bin/python
``

**Comment by frostming** [comment] 2022-01-21 12:45
> Isn’t this:
> 
> ```diff
> ---
>  tests/test_project.py |    4 +---
>  1 file changed, 1 insertion(+), 3 deletions(-)
> 
> --- a/tests/test_project.py
> +++ b/tests/test_project.py
> @@ -211,6 +211,4 @@ def test_global_python_path_config(proje
>  def test_set_non_exist_python_path(project_no_init):
>      project_no_init.project_config["python.path"] = "non-exist-python"
>      project_no_init._python = None
> -    assert os.path.normcase(project_no_init.python.executable) == os.path.normcase(
> -        sys.executable
> -    )
> +    assert os.path.normcase(sys.executable).startswith(os.path.normcase(project_no_init.python.executable))
> ```
> 
> solution for the first test?

I'm fine with it, care to submit a PR?

**Comment by mcepl** [comment] 2022-01-21 12:54
> > solution for the first test?
> 
> I'm fine with it, care to submit a PR?

Are you? Shouldn’t we fix the `project_no_init.python.executable` to have correct value?

**Comment by frostming** [comment] 2022-01-21 14:24
> > > solution for the first test?
> > 
> > 
> > I'm fine with it, care to submit a PR?
> 
> Are you? Shouldn’t we fix the `project_no_init.python.executable` to have correct value?

First you have to define what is correct, because `/usr/bin/python` `/usr/bin/python3` and `/usr/bin/python3.10` all exist and are equal, the `pythonfinder` just picks one from them. `sys.executable` is what PDM is using, and it is not always "correct" for that purpose.

**Comment by mcepl** [comment] 2022-01-21 14:30
> First you have to define what is correct, because `/usr/bin/python` `/usr/bin/python3` and `/usr/bin/python3.10` all exist and are equal, the `pythonfinder` just picks one from them. `sys.executable` is what PDM is using, and it is not always "correct" for that purpose.

1. `/usr/bin/python` doesn’t have to exist at all, and in fact my interpretation of https://www.python.org/dev/peps/pep-0394/#for-python-runtime-distributors is such that openSUSE doesn’t link the current Python 3 interpreter to `/usr/bin/python`, and that remains just for Python 2 (and actually we encourage our users, if they want to have ``python`` as a command, they should make themselves symlink to ``/usr/local/bin/python`` instead).

2. Yes, `/usr/bin/python3` should exist always, at least as a symlink to the primary interpreter of Python 3 (3.8 currently at openSUSE and moving towards 3.10).

3. Does `/usr/bin/python3.10` have to exist? Isn’t it just for weird multiple-Python installations like openSUSE?

**Comment by mweinelt** [comment] 2022-01-21 16:16
In our world `/usr/bin` doesn't have to exist at all, but you can expect `python`, `python3` and `python3.9` (or other respective versions) to be available in the `PATH`. Should we just disable this test on our end in that case or is looking at the `PATH` the more reasonable approach here anyway?

```
❯ which python3
/etc/profiles/per-user/hexa/bin/python3
❯ readlink $(which python)
/nix/store/dn4fwp0yx6nsa85cr20cwvdmg64xwmcy-python3-3.9.9/bin/python
```

**Comment by frostming** [comment] 2022-01-24 03:18
I marked some cases with `pytest.mark.path` for skipping.

**Comment by mcepl** [comment] 2022-01-24 09:36
Better, still missing `test_show_self_package`:
```
[  656s] =================================== FAILURES ===================================
[  656s] ____________________________ test_show_self_package ____________________________
[  656s]
[  656s] project = <Project '/tmp/pytest-of-abuild/pytest-0/test_show_self_package0'>
[  656s] invoke = <function invoke.<locals>.caller at 0x7f4d89b11af0>
[  656s]
[  656s]     def test_show_self_package(project, invoke):
[  656s]         result = invoke(["show"], obj=project)
[  656s]         assert result.exit_code == 0, result.stderr
[  656s]
[  656s]         result = invoke(["show", "--name", "--version"], obj=project)
[  656s]         assert result.exit_code == 0
[  656s] >       assert "test_project\n0.0.0\n" == result.output
[  656s] E       AssertionError: assert 'test_project\n0.0.0\n' == '    test_pro...\n    0.0.0\n'
[  656s] E         -     test_project
[  656s] E         ? ----
[  656s] E         + test_project
[  656s] E         -     0.0.0
[  656s] E         ? ----
[  656s] E         + 0.0.0
[  656s]
[  656s] tests/cli/test_others.py:283: AssertionError
[  656s] ---------------------------- Captured stdout setup -----------------------------
[  656s]     Using Python interpreter: /usr/bin/python3.9 (3.9)
[  656s]     Changes are written to pyproject.toml.
[  656s] ------------------------------ Captured log call -------------------------------
```

**Comment by frostming** [comment] 2022-01-24 09:43
@mcepl It is appreciated if you can help debug why are those lines are indented because I can't reproduce both locally or CI. There must be some bugs hiding there.

**Comment by frostming** [comment] 2022-02-16 10:03
Close it for now. Please open a new issue if you encounter any problem.

**Closed by frostming** 2022-02-16 10:03 UTC
Labels: bug
