### ISSUE TITLE
`pdm run` will disable the KeyboardInterrupt

### ISSUE THREAD

**Issue by RF-Tar-Railt** [pdm-project/pdm#2145] opened 2023-07-30 02:36 UTC
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

If there is a program with a pending loop (like `uvicorn.run`), after first `pdm run`, when starting the program through `pdm run ...` or `python ...`, the KeyboardInterrupt cannot be captured, resulting in the inability to close the program in the console. If turn off the console, it will cause the program to continue running in the background, like ghost.

## Actual behavior

The program will keep running, because it cannot be closed by `ctrl c` in the console (which in Windows. The behavior in other os may be different)

## Expected behavior

The program will always exit normally

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.8.1
Python Interpreter:
  D:\Download\Projects\nonebot_plugin_alconna\.venv\Scripts\python.exe (3.9)
Project Root:
  D:/Download/Projects/nonebot_plugin_alconna/
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.9.13",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19045",
  "python_full_version": "3.9.13",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "win32"
}
```

**Comment by RF-Tar-Railt** [comment] 2023-07-30 03:15
in Linux (e.g. wsl2), program using `uvicorn.run` will raise `asyncio.exceptions.CancelledError`

**Comment by dranjan** [comment] 2023-08-10 23:45
Same issue perhaps? https://github.com/pdm-project/pdm/issues/1768

**Comment by frostming** [comment] 2023-08-11 02:00
> > Same issue perhaps? #1768
> 
> ![image](https://user-images.githubusercontent.com/42648639/259906974-a441aaaf-1c08-4685-bcff-31063d971b55.png)

From this screenshot it seems no problem. `pdm run python` behaves the same as `python`

**Comment by RF-Tar-Railt** [comment] 2023-08-11 02:00
> Same issue perhaps? #1768

look this

```python
import traceback

try:
    while True:
        tmp = input(">>>")
        if tmp == "exit":
            exit()
except BaseException:
    traceback.print_exc()
    print("exception caught; exiting.")
```
behavior when use `python`:
```
 ~#@❯ python .\test-pdm.py
>>>exit
Traceback (most recent call last):
  File "D:\Download\Projects\Avilla\test-pdm.py", line 7, in <module>
    exit()
  File "C:\Users\TR\AppData\Local\Programs\Python\Python39\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None
exception caught; exiting.
 ~#@❯ python .\test-pdm.py
>>>Traceback (most recent call last):
  File "D:\Download\Projects\Avilla\test-pdm.py", line 5, in <module>
    tmp = input(">>>")
KeyboardInterrupt
exception caught; exiting.
```

behavior when use `pdm run`:
```
 ~#@❯ pdm run .\test-pdm.py
>>>exit
Traceback (most recent call last):
  File "D:\Download\Projects\Avilla\test-pdm.py", line 7, in <module>
    exit()
  File "C:\Users\TR\AppData\Local\Programs\Python\Python39\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None
exception caught; exiting.
 ~#@❯ pdm run .\test-pdm.py
>>>Traceback (most recent call last):
  File "D:\Download\Projects\Avilla\test-pdm.py", line 5, in <module>
    tmp = input(">>>")
EOFError
exception caught; exiting.
```

behavior when use `python` after `pdm run`
```
 ~#@❯ python .\test-pdm.py
>>>exit
Traceback (most recent call last):
  File "D:\Download\Projects\Avilla\test-pdm.py", line 7, in <module>
    exit()
  File "C:\Users\TR\AppData\Local\Programs\Python\Python39\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None
exception caught; exiting.
 ~#@❯ python .\test-pdm.py
>>>Traceback (most recent call last):
  File "D:\Download\Projects\Avilla\test-pdm.py", line 5, in <module>
    tmp = input(">>>")
EOFError
exception caught; exiting.
```

**Comment by frostming** [comment] 2023-08-11 02:08
This is what I got with pdm 2.8.2 and python3.11.3
```
PS C:\Users\frost\wkspace\test-pdm> pdm run .\script.py
>>>1
>>>2
>>>Traceback (most recent call last):
  File "C:\Users\frost\wkspace\test-pdm\script.py", line 5, in <module>
    tmp = input(">>>")
          ^^^^^^^^^^^^
KeyboardInterrupt
exception caught; exiting.
```

**Comment by RF-Tar-Railt** [comment] 2023-08-11 02:09
> This is what I got with pdm 2.8.2 and python3.11.3
> 
> ```
> PS C:\Users\frost\wkspace\test-pdm> pdm run .\script.py
> >>>1
> >>>2
> >>>Traceback (most recent call last):
>   File "C:\Users\frost\wkspace\test-pdm\script.py", line 5, in <module>
>     tmp = input(">>>")
>           ^^^^^^^^^^^^
> KeyboardInterrupt
> exception caught; exiting.
> ```

how about exec twice?

**Comment by frostming** [comment] 2023-08-11 02:10
> how about exec twice?

what do you mean by exec twice, the result doesn't change for second trial.

**Comment by RF-Tar-Railt** [comment] 2023-08-11 02:11
> > how about exec twice?
> 
> what do you mean by exec twice, the result doesn't change for second trial.

```
 ~#@❯ pdm run .\test-pdm.py
>>>Traceback (most recent call last):
  File "D:\Download\Projects\Avilla\test-pdm.py", line 5, in <module>
    tmp = input(">>>")
KeyboardInterrupt
exception caught; exiting.
 ~#@❯ pdm run .\test-pdm.py
>>>Traceback (most recent call last):
  File "D:\Download\Projects\Avilla\test-pdm.py", line 5, in <module>
    tmp = input(">>>")
EOFError
exception caught; exiting.
```

**Comment by frostming** [comment] 2023-08-11 02:13
It doesn't change no matter how many times I tried(I actually tried 10 times).

It doesn't make sense either since it is stateless.

**Comment by RF-Tar-Railt** [comment] 2023-08-11 02:16
> It doesn't change no matter how many times I tried(I actually tried 10 times).
> 
> It doesn't make sense either since it is stateless.

try using exec in powershell ?

**Comment by frostming** [comment] 2023-08-11 02:17
> > It doesn't change no matter how many times I tried(I actually tried 10 times).
> > It doesn't make sense either since it is stateless.
> 
> try using exec in powershell ?

It is powershell(see the prompt in my exec result) on a windows server VM, because I don't have windows machine myself.

**Comment by RF-Tar-Railt** [comment] 2023-08-11 02:20
It is normal when use command prompt rather abnormal when use powershell

**Comment by frostming** [comment] 2023-08-11 02:21
> It is normal when use command prompt rather abnormal when use powershell

Could it be caused by your shell setup(plugins)?

**Comment by RF-Tar-Railt** [comment] 2023-08-11 02:29
> > It is normal when use command prompt rather abnormal when use powershell
> 
> Could it be caused by your shell setup(plugins)? Or could you think of a better way than the current approach to propagate the signals to the subprocess? Or we could do little about this.

you are right, my powershell uses oh-my-posh. pure powershell is normal, too.

**Comment by frostming** [comment] 2023-08-11 02:30
> you are right, my powershell uses oh-my-posh. pure powershell is normal, too.

Oh that is quite weird. So I am going to close the issue if you don't have other concerns.

**Closed** 2023-08-11 02:36 UTC
Labels: bug
