### ISSUE TITLE
Unable to read multiple platform-specific entries for single dependency from `pyproject.toml`

### ISSUE THREAD

**Issue by rohansatapathy** [pdm-project/pdm#2661] opened 2024-03-02 01:34 UTC
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. Install PDM on a macOS system
2. Run `pdm init`, accepting all default values
3. Add the following to the dependencies table in `pyproject.toml`:

    ```toml
    dependencies = [
        "numpy==1.26; platform_system != 'Windows'",
        "numpy==1.25; platform_system == 'Windows'",
    ]

    ```
4. Run `pdm install -v`

## Actual behavior

PDM doesn't install `numpy` at all.

Output of `pdm install -v`:
```
WARNING: Lockfile does not exist
Updating the lock file...
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   numpy==1.25; platform_system == "Windows"
pdm.termui:   python>=3.10
pdm.termui:   Adding requirement numpy==1.25; platform_system == "Windows"
pdm.termui:   Adding requirement python>=3.10
pdm.termui: ======== Starting round 0 ========
STATUS: Resolving: new pin python>=3.10
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
STATUS: Resolving: new pin numpy 1.25.0
pdm.termui: Pinning: numpy 1.25.0
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:   python None
pdm.termui:    numpy 1.25.0
STATUS: Fetching hashes for resolved packages...
pdm.termui: Fetching hashes for numpy@1.25.0
🔒 Lock successful
Changes are written to pdm.lock.
STATUS: Resolving packages from lockfile...
All packages are synced to date, nothing to do.

🎉 All complete!
```
Contents of `pdm.lock`:
```
# This file is @generated by PDM.
# It is not intended for manual editing.

[metadata]
groups = ["default"]
strategy = ["cross_platform", "inherit_metadata"]
lock_version = "4.4.1"
content_hash = "sha256:5e595dc6e9b1fb8a37699cd84750eab0f16f6cfabf99e8d04282e00403ac8cd8"

[[package]]
name = "numpy"
version = "1.25.0"
requires_python = ">=3.9"
summary = "Fundamental package for array computing in Python"
groups = ["default"]
marker = "platform_system == \"Windows\""
files = [
    {file = "numpy-1.25.0-cp310-cp310-macosx_10_9_x86_64.whl", hash = "sha256:8aa130c3042052d656751df5e81f6d61edff3e289b5994edcf77f54118a8d9f4"},
    {file = "numpy-1.25.0-cp310-cp310-macosx_11_0_arm64.whl", hash = "sha256:9e3f2b96e3b63c978bc29daaa3700c028fe3f049ea3031b58aa33fe2a5809d24"},
    {file = "numpy-1.25.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl", hash = "sha256:d6b267f349a99d3908b56645eebf340cb58f01bd1e773b4eea1a905b3f0e4208"},
    {file = "numpy-1.25.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:4aedd08f15d3045a4e9c648f1e04daca2ab1044256959f1f95aafeeb3d794c16"},
    {file = "numpy-1.25.0-cp310-cp310-musllinux_1_1_x86_64.whl", hash = "sha256:6d183b5c58513f74225c376643234c369468e02947b47942eacbb23c1671f25d"},
    {file = "numpy-1.25.0-cp310-cp310-win32.whl", hash = "sha256:d76a84998c51b8b68b40448ddd02bd1081bb33abcdc28beee6cd284fe11036c6"},
    {file = "numpy-1.25.0-cp310-cp310-win_amd64.whl", hash = "sha256:c0dc071017bc00abb7d7201bac06fa80333c6314477b3d10b52b58fa6a6e38f6"},
    {file = "numpy-1.25.0-cp311-cp311-macosx_10_9_x86_64.whl", hash = "sha256:4c69fe5f05eea336b7a740e114dec995e2f927003c30702d896892403df6dbf0"},
    {file = "numpy-1.25.0-cp311-cp311-macosx_11_0_arm64.whl", hash = "sha256:9c7211d7920b97aeca7b3773a6783492b5b93baba39e7c36054f6e749fc7490c"},
    {file = "numpy-1.25.0-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl", hash = "sha256:ecc68f11404930e9c7ecfc937aa423e1e50158317bf67ca91736a9864eae0232"},
    {file = "numpy-1.25.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:e559c6afbca484072a98a51b6fa466aae785cfe89b69e8b856c3191bc8872a82"},
    {file = "numpy-1.25.0-cp311-cp311-musllinux_1_1_x86_64.whl", hash = "sha256:6c284907e37f5e04d2412950960894b143a648dea3f79290757eb878b91acbd1"},
    {file = "numpy-1.25.0-cp311-cp311-win32.whl", hash = "sha256:95367ccd88c07af21b379be1725b5322362bb83679d36691f124a16357390153"},
    {file = "numpy-1.25.0-cp311-cp311-win_amd64.whl", hash = "sha256:b76aa836a952059d70a2788a2d98cb2a533ccd46222558b6970348939e55fc24"},
    {file = "numpy-1.25.0-pp39-pypy39_pp73-macosx_10_9_x86_64.whl", hash = "sha256:5b1b90860bf7d8a8c313b372d4f27343a54f415b20fb69dd601b7efe1029c91e"},
    {file = "numpy-1.25.0-pp39-pypy39_pp73-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:85cdae87d8c136fd4da4dad1e48064d700f63e923d5af6c8c782ac0df8044542"},
    {file = "numpy-1.25.0-pp39-pypy39_pp73-win_amd64.whl", hash = "sha256:cc3fda2b36482891db1060f00f881c77f9423eead4c3579629940a3e12095fe8"},
    {file = "numpy-1.25.0.tar.gz", hash = "sha256:f1accae9a28dc3cda46a91de86acf69de0d1b5f4edd44a9b0c3ceb8036dfff19"},
]
```

## Expected behavior

PDM should recognize that `platform_system == 'Darwin'` and install `numpy==1.26`. This is the behavior that `pip` currently exhibits.
```bash
$ pip install -e .
Obtaining file:///Users/rohansatapathy/code/rohansatapathy/pdm_test
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting numpy==1.26 (from pdm_test==0.1.0+editable)
  Downloading numpy-1.26.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.5/53.5 kB 919.6 kB/s eta 0:00:00
Downloading numpy-1.26.0-cp310-cp310-macosx_11_0_arm64.whl (14.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 17.6 MB/s eta 0:00:00
Building wheels for collected packages: pdm_test
  Building editable for pdm_test (pyproject.toml) ... done
  Created wheel for pdm_test: filename=pdm_test-0.1.0+editable-py3-none-any.whl size=1335 sha256=94f0884368aa1a019d93e85cb0552e48c28012b1e8e004a6f79c3c513e1e5243
  Stored in directory: /private/var/folders/qx/d2w7vcyd68531v5vdnm4xw2h0000gn/T/pip-ephem-wheel-cache-2vyn27pt/wheels/e2/c5/6d/0e8626ce27e76d37886518276ada971b5f47d6dff7610da6db
Successfully built pdm_test
Installing collected packages: numpy, pdm_test
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.0
    Uninstalling numpy-1.24.0:
      Successfully uninstalled numpy-1.24.0
  Attempting uninstall: pdm_test
    Found existing installation: pdm_test 0.1.0+editable
    Uninstalling pdm_test-0.1.0+editable:
      Successfully uninstalled pdm_test-0.1.0+editable
Successfully installed numpy-1.26.0 pdm_test-0.1.0+editable
WARNING: There was an error checking the latest version of pip.
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
$ pdm info && pdm info --env
PDM version:
  2.12.4
Python Interpreter:
  /Users/rohansatapathy/code/rohansatapathy/pdm_test/.venv/bin/python (3.10)
Project Root:
  /Users/rohansatapathy/code/rohansatapathy/pdm_test
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.10.12",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "23.0.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:57 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8112",
  "python_full_version": "3.10.12",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment] 2024-03-02 01:44
That's non-trivial that you'd think. Installation time evaluation is easy, but both dependency specification must be resolved and pinned in the lockfile. It is indeed duplicate of #46

**Closed** 2024-03-02 01:45 UTC
Labels: 🐛 bug
